<div id="back_white_main">	

	<h2 class="cufon_h2">User Management</h2>
		
		  
          <table class="backend_show_book" cellpadding="0" cellspacing="0" border="0" width="100%">
            <tr class="head">
              <th>ID</th>
              <th>Email</th>
              <th>First Name</th>
              <th>Last  Name</th>
            </tr>
            
            <?php foreach( $this->users as $user ):?>
            <tr>
              <td><?php echo $user['id']?></td>
              <td><?php echo $user['email']?></td>
              <td><?php echo $user['first_name']?></td>
              <td><?php echo $user['last_name']?></td>
          
            </tr>
            <?php endforeach;?>
            
		 </table>
		 <?php if($this->pagination):?>
			 <?php echo $this->pagination ?>
		 <?php endif;?>
		 
</div>


	
	
