			<td width="81%" align="center" valign="top"><!-- InstanceBeginEditable name="EditRegion1" -->
                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td>&nbsp;</td>
                  </tr>
                  <tr>
                    <td><div align="center">
                      <table cellspacing="0" cellpadding="0">
                        <tr>
                          <td height="80"><div align="center" class="STYLE5">Chi Institute and China National Society of   TCVM <br />
                                 Certified Veterinary Acupuncturist (CVA) </div></td>
                        </tr>
                        <tr>
                          <td align="middle"><img border="0" src="images/cert1.jpg" width="502" height="384" /></td>
                        </tr>
                      </table>
                      </div></td>
                  </tr>
                  <tr>
                    <td>&nbsp;</td>
                  </tr>
                  <tr>
                    <td><div align="center" class="STYLE4">Requirements of Certified Veterinary   Acupuncturist </div>
                      <table border="0" cellspacing="0" cellpadding="0" width="500" align="center">
                        <tbody>
                          <tr>
                            <td></td>
                          </tr>
                          <tr>
                            <td class="STYLE10"><div align="left">1. Take all sessions of <a href="/Program/program_basic.htm">Veterinary Acupuncture Program</a>.<br />
                              2. The   score of Veterinary Acupuncture Program Written Test is above 70.<br />
                              3. The   score of Acupoint ID Exam is above 70.<br />
                              4. Acupuncture Case Report is   approved.<br />
                              5. *30-Hour <a href="/Program/program_advanced.htm">TCVM Advanced Program Training</a> or <a href="/doc/InternShip.pdf" target="_blank">30-hour Internship with a   certified Veterinary Acupuncturist</a> is approved. (please refer suggestions   below)</div></td>
                          </tr>
                        </tbody>
                      </table></td>
                  </tr>
                </table>
              <!-- InstanceEndEditable --></td>