<td width="81%" align="center" valign="top"><!-- InstanceBeginEditable name="EditRegion1" -->
                <div align="center"></div>
                <table width="750" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td><table width="95%" border="0" align="center" cellpadding="0" cellspacing="0">
                      <tr>
                        <td height="50"><div align="center" class="STYLE5">Moxibustion </strong></div></td>
                      </tr>
                      <tr>
                        <td><p align="left" class="STYLE2">Moxibustion is a method by which moxa punk or other herbs are burned on or above the skin near acupuncture points. The heat and herbal essence warms the Qi and Blood in the channels and collaterals and thus increases the flow during times of stasis.Moxibustion also invigorates the Yang Qi and dispels internal Cold and Dampness as well as eliminates some forms of local Heat Toxin.</p>
                          <p align="left" class="STYLE2">There are two general methods of moxibustion therapy, direct and indirect. For direct moxibustion, moxa material (“wool”) is shaped into cones, threads or “rice” and placed directly on skin over an acupuncture point. Sometimes a tenacious material such as aloe gel or petrolatum jelly is first rubbed on the point so the moxa wool sticks to area it is placed. Direct moxa is common in human practice and can be either scarring or nonscarring.</p>
                          <p align="left" class="STYLE2">Since verbal feedback of heat intensity (which changes from imperceptible to too hot almost instantaneously!) is lacking in non-human patients, direct moxa is rarely used in veterinary acupuncture practice.Indirect moxibustion therapy is done by the veterinary acupuncturist as either needle moxa (“warming needle”) or moxa stick therapy. Needle moxa is done using a moxa wool ball that is placed on the top of a previously inserted acupuncture needle. The moxa is lit closest to the skin and allowed to burn and add warmth to the inserted needles’ handle and shaft. Some practitioners use a piece of foil at the needle insertion point near skin level to catch any burning embers which might fall from the burning moxa ball.</p>
                          <p align="left" class="STYLE2">The most common form of indirect moxibustion therapy used in veterinary acupuncture practice is indirect stick moxa. Pre-rolled moxa sticks of mugwort (Artemisia vulgaris) mixed with small amounts of other herbs such as cinnamon, dried ginger, cloves, myrrh and frankincense are available for inexpensive bulk purchase.</p>
                          <p align="left" class="STYLE2">These sticks are about 6 inches long and resemble a cigar. They are lit on one end until there is a burning ember and then moved close to the skin above a known acupuncture <span class="STYLE2">point</span>.</p>
                          <p align="left"></p>
                          <p align="left">&nbsp;</p>                          </td>
                      </tr>
                    </table></td>
                  </tr>
                </table>
                <!-- InstanceEndEditable --></td>