<td width="81%" align="center" valign="top"><!-- InstanceBeginEditable name="EditRegion1" -->
                <div align="center"></div>
                <table width="750" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td><div align="center">
                      <table width="95%" border="0" cellspacing="0" cellpadding="0">
                        <tr>
                          <td height="50"><div align="center" class="STYLE5">Qi gong</div></td>
                        </tr>
                        <tr>
                          <td class="STYLE2"><p align="left"><span lang="EN-US" xml:lang="EN-US">Qigong may be   defined as “any training or study dealing with Qi which takes a long time and a   lot of effort. The ability to concentrate and generate consistent   useful energy may benefit all health care providers with regard for their own   health as well as that of their patients.</span></p>
                            <p align="left"><span lang="EN-US" xml:lang="EN-US">-QI Gong: Soft, slow, repetative movement and breathing   exercises</span></p></td>
                        </tr>
                      </table>
                    </div></td>
                  </tr>
                </table>
                <!-- InstanceEndEditable --></td>