			<td width="81%" align="center" valign="top"><!-- InstanceBeginEditable name="EditRegion1" -->
                <table width="750" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td><img src="<?php echo $this->baseUrl() ?>/images/c1.jpg" width="240" height="216" /></td>
                    <td width="15">&nbsp;</td>
                    <td><table width="240" height="216" border="0" cellpadding="0" cellspacing="0">
                        <tr>
                          <td height="114"><a target="_blank" href="http://pets.groups.yahoo.com/group/chiacupuncture/"><img src="<?php echo $this->baseUrl() ?>/images/c2.jpg" width="240" height="216" border="0" /></a></td>
                        </tr>
                        
                    </table></td>
                    <td width="15">&nbsp;</td>
                    <td><a href="<?php echo $this->url(array("action" => "index" , "controller" => "courses"), 'default', true);?>"><img src="<?php echo $this->baseUrl() ?>/images/c3.jpg" width="240" height="216" border="0" /></a></td>
                  </tr>
                </table>
                <table width="750" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                  </tr>
                  <tr>
                    <td width="495" height="156" valign="top" background="images/c44.jpg"><table width="495" height="1" border="0" cellpadding="10" cellspacing="0">
                      <tr>
                        <td width="283" class="STYLE10"><div align="left">
                          <p align="justify">The Chi Institute believes that the best   veterinary health care is the integration of TCVM and conventional veterinary   medical care, as unique advantages exist in both systems. Thus, the Chi   Institute provides a high quality curriculum that will enable veterinarians to   effectively apply the TCVM approach as an integral part of their practice......</p>
                          </div></td>
                        <td width="172" align="left" valign="top" class="STYLE2"><p><br />
                                <br />
                        </p></td>
                      </tr>
                    </table></td>
                    <td width="15">&nbsp;</td>
                    <td valign="top" background="images/payment2.jpg"><table width="240" height="1" border="0" cellpadding="0" cellspacing="0">
                      <tr>
                        <td width="5" height="25" rowspan="2">&nbsp;</td>
                        <td width="168" height="25" align="left" valign="bottom" class="STYLE3">Payment</td>
                      </tr>
                      <tr>
                        <td height="13" align="left" class="STYLE2">pay for your registration with</td>
                      </tr>
                      <tr>
                        <td height="100">&nbsp;</td>
                        <td height="1" align="left" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="2">
                          <tr>
                            <td><select name="select3" class="input1">
                                <option>cred it card</option>
                            </select></td>
                          </tr>
                          <tr>
                            <td><img src="<?php echo $this->baseUrl() ?>/images/find.gif" width="24" height="19" /></td>
                          </tr>
                        </table></td>
                      </tr>
                    </table></td>
                  </tr>
                </table>
                <table width="750" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td>&nbsp;</td>
                  </tr>
                </table>
                <table width="750" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td width="50%" align="left"><table width="90%" border="0" cellspacing="0" cellpadding="0">
                        <tr>
                          <td width="115"><a href="http://www.naturalvet.org/service_tuina.htm"><img src="<?php echo $this->baseUrl() ?>/images/D1.jpg" width="115" height="81" border="0" /></a></td>
                          <td width="10">&nbsp;</td>
                          <td align="left" valign="top" class="STYLE2"><span class="STYLE4">Tui Na</span> <br />
                            actually means “push/pull-lift” and refers to two of the primary   techniques in this complex system ...... </td>
                        </tr>
                        <tr>
                          <td class="xx">&nbsp;</td>
                          <td class="xx">&nbsp;</td>
                          <td align="left" valign="top" class="xx">&nbsp;</td>
                        </tr>
                        <tr class="xx">
                          <td>&nbsp;</td>
                          <td>&nbsp;</td>
                          <td align="left" valign="top" class="STYLE2">&nbsp;</td>
                        </tr>
                    </table></td>
                    <td width="50%" align="left"><table width="90%" border="0" cellspacing="0" cellpadding="0">
                        <tr>
                          <td width="115" valign="top"><a href="http://www.naturalvet.org/service_food.htm"><img src="<?php echo $this->baseUrl() ?>/images/D2.jpg" width="115" height="81" border="0" /></a></td>
                          <td width="10">&nbsp;</td>
                          <td align="left" valign="top" class="STYLE2"><span class="STYLE4">Food therapy </span> <br />
                            Most companion animal caretakers have been educated to believe that a   highly-processed cereal product called “pet food” is adequate food for....</td>
                        </tr>
                        <tr>
                          <td class="xx">&nbsp;</td>
                          <td class="xx">&nbsp;</td>
                          <td align="left" valign="top" class="xx">&nbsp;</td>
                        </tr>
                        <tr class="xx">
                          <td>&nbsp;</td>
                          <td>&nbsp;</td>
                          <td align="left" valign="top" class="STYLE2">&nbsp;</td>
                        </tr>
                    </table></td>
                  </tr>
                  <tr>
                    <td align="left"><table width="90%" border="0" cellspacing="0" cellpadding="0">
                        <tr>
                          <td width="115"><a href="http://www.naturalvet.org/service_acu.htm"><img src="<?php echo $this->baseUrl() ?>/images/D3.jpg" width="115" height="81" border="0" /></a></td>
                          <td width="10">&nbsp;</td>
                          <td align="left" valign="top" class="STYLE2"><span class="STYLE4">Acupuncture</span> <br />
                            the 2,300 year old Traditional Chinese Medical art and science of using small   needles inserted into specific body points to effect healing changes......</td>
                        </tr>
                        <tr>
                          <td class="xx">&nbsp;</td>
                          <td class="xx">&nbsp;</td>
                          <td align="left" valign="top" class="xx">&nbsp;</td>
                        </tr>
                        <tr class="xx">
                          <td>&nbsp;</td>
                          <td>&nbsp;</td>
                          <td align="left" valign="top" class="STYLE2">&nbsp;</td>
                        </tr>
                    </table></td>
                    <td align="left"><table width="90%" border="0" cellspacing="0" cellpadding="0">
                        <tr>
                          <td width="115"><a href="<?php echo $this->url(array(), 'qigong', true);?>"><img src="<?php echo $this->baseUrl() ?>/images/D4.jpg" width="115" height="81" border="0" /></a></td>
                          <td width="10">&nbsp;</td>
                          <td align="left" valign="top" class="STYLE2"><span class="STYLE4">Qigong</span> <br />
                            <span lang="EN-US" xml:lang="EN-US">Soft, slow, repetative movement and breathing exercises</span>......</td>
                        </tr>
                        <tr>
                          <td class="xx">&nbsp;</td>
                          <td class="xx">&nbsp;</td>
                          <td align="left" valign="top" class="xx">&nbsp;</td>
                        </tr>
                        <tr class="xx">
                          <td>&nbsp;</td>
                          <td>&nbsp;</td>
                          <td align="left" valign="top" class="STYLE2">&nbsp;</td>
                        </tr>
                    </table></td>
                  </tr>
                  <tr>
                    <td align="left"><table width="90%" border="0" cellspacing="0" cellpadding="0">
                        <tr>
                          <td width="115"><a href="<?php echo $this->url(array(), 'moxibustion', true);?>"><img src="<?php echo $this->baseUrl() ?>/images/D6.jpg" width="115" height="81" border="0" /></a></td>
                          <td width="10">&nbsp;</td>
                          <td align="left" valign="top" class="STYLE2"><span class="STYLE4">Moxibustion</span> <br />
                            a method by which moxa punk or other herbs are burned on or above the skin near acupuncture points......</td>
                        </tr>
                        <tr class="xx">
                          <td class="xx">&nbsp;</td>
                          <td class="xx">&nbsp;</td>
                          <td align="left" valign="top" class="xx">&nbsp;</td>
                        </tr>
                        <tr>
                          <td>&nbsp;</td>
                          <td>&nbsp;</td>
                          <td align="left" valign="top">&nbsp;</td>
                        </tr>
                    </table></td>
                    <td align="left"><table width="90%" border="0" cellspacing="0" cellpadding="0">
                        <tr>
                          <td width="115"><img src="<?php echo $this->baseUrl() ?>/images/d5.jpg" width="115" height="81" /></td>
                          <td width="10">&nbsp;</td>
                          <td align="left" valign="top" class="STYLE2"><span class="STYLE4">Other</span> <br />
                            Comming soon <br /></td>
                        </tr>
                        <tr>
                          <td class="xx">&nbsp;</td>
                          <td class="xx">&nbsp;</td>
                          <td align="left" valign="top" class="xx">&nbsp;</td>
                        </tr>
                        <tr class="xx">
                          <td>&nbsp;</td>
                          <td>&nbsp;</td>
                          <td align="left" valign="top" class="STYLE2">&nbsp;</td>
                        </tr>
                    </table></td>
                  </tr>
                </table>
              <!-- InstanceEndEditable -->
             </td>