<div id="back_main">
		<h2 class="cufon_h2">Courses Edit</h2>

		<form class="form" action="<?php echo $this->url(array(
				'controller' => 'courses', 
				'action' => 'postsave', 
				'module' => 'admin'
				), null , true);?>" 
				method="post">
						
		<input type="hidden" value="<?php if( $this->courses )echo $this->courses['id']?>" name="id" id="id" />
		<input type="hidden" name="image" id="image" />
		
		<div>
		<label>Name:</label>
		<input name="name" id="name" type="text" value="<?php if( $this->courses )echo $this->courses['name']?>"></input>
		</div>
		
		
		<div>
		<label>Description:</label>
		<textarea name="desc" id="desc"><?php if( $this->courses )echo htmlspecialchars_decode(stripslashes($this->courses['desc']));?></textarea>
		</div>
		

		
		<div>
		<label>Start Date:</label>
		<input name="time_start" id="time_start" type="text" value="<?php if( $this->courses )echo date("d-m-Y", $this->courses['time_start_int'] )?>"></input>
		</div>
		
		<div>
		<label>End Date:</label>
		<input name="time_end" id="time_end" type="text" value="<?php if( $this->courses )echo date("d-m-Y", $this->courses['time_end_int'] )?>"></input>
		</div>
		
		<div>
		<label>Discount Price:</label>
		<input name="before_price" id="before_price" type="text" value="<?php if( $this->courses )echo $this->courses['before_price']?>"></input>
		</div>
		
		<div>
		<label>Normal Price:</label>
		<input name="now_price" id="now_price" type="text" value="<?php if( $this->courses )echo $this->courses['now_price']?>"></input>
		</div>
		
		<div>
		<label>Visible:</label>
		<select name="visible" id="visible">
			<option value="1">Visible</option>
			<option value="0">Disable</option>
		</select>
		</div>
		
		<div>
		<label>Paypal:</label>
		<select name="paypal" id="paypal">
			<option value="au">AU</option>
			<option value="us">US</option>
		</select>
		</div>
		
		
		<div>
		<label>Images:( 111*79 )</label>
			<div id="imagearea">
			</div>
		</div>
		
		<?php if( $this->courses && $this->courses['image'] ):?>
		<div style="display:block">
		<?php else:?>
		<div style="display:none">
		<?php endif;?>
			<img id="imagesrc" src="<?php if($this->courses) echo $this->baseUrl() . $this->courses['image'] ; ?>"></img>
		</div>
		

		<div class="for_align_right">
		<input type="submit" value="Submit" class="back_btn"/>
		</div>		

		</form>
		
</div>

<script>

	$("#time_start").datepicker({ dateFormat: 'dd-mm-yy' });
	$("#time_end").datepicker({ dateFormat: 'dd-mm-yy' });

	<?php if($this->courses):?>
		$("#visible").val(<?php echo $this->courses['visible']?>);
		$("#paypal").val("<?php echo $this->courses['paypal']?>");
	<?php endif; ?>

	//header image swfupload
	var swf = $("#imagearea").swfupload({
		
		upload_url 			: __BASE_URL__ + "/admin/index/imageupload",
		flash_url	  		: __BASE_URL__ + "/js/rocknoon/jplugin/jquery.swfupload/swfupload.swf",
		button_image_url 	: __BASE_URL__ + "/js/rocknoon/jplugin/jquery.swfupload/upload_bt.gif",
		complete_handler    : rocknoon.callback( this , 'complete_imageupdate' )
	});

	//after image update callback function
	function complete_imageupdate( rst ){
		if( rst.error ){
			alert( rst.error );
		}else{
			$("#imagesrc").attr( "src" , __BASE_URL__ + rst.imageUrl );
			$("#imagesrc").parent().show();
			$("#image").attr( "value" , rst.imageUrl );
		}	
	}

	
	
	
</script>