			<td width="81%" align="center" valign="top"><!-- InstanceBeginEditable name="EditRegion1" -->
                <div align="center"></div>
                <table width="750" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td>
                      <p align="center" class="STYLE5">Error</p>
                      <table width="80%" border="0" align="center" cellpadding="0" cellspacing="0" style="margin-bottom:20px;" >
                          <tr>
                            <td>
                            <div class="SUCCESS">
                            <?php if( APPLICATION_ENV != "production" ):?>
                            <?php echo $this->error?>
                            <?php else:?>
                            Sorry, the credit card information you fill in is not correct.
                            <?php endif;?>
							</div>
                    		</td>
                          </tr>
                    </table>
                    </td>
                    
                  </tr>
                </table>
                <!-- InstanceEndEditable -->
            </td>