			<td width="81%" align="center" valign="top"><!-- InstanceBeginEditable name="EditRegion1" -->
                <div align="center"></div>
                <table width="750" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
                      <tr>
                        <td height="50"><div align="center" class="STYLE5">Credit Card </div></td>
                        </tr>
                      <tr>
                        <td><div align="center">
                          <form onsubmit="return checkForm();" action="<?php echo $this->url(array("action" => "do-paypal-direct-pay" , "controller" => "pay"), 'default', true);?>" method="post" enctype="multipart/form-data" name="form1" id="form1">
                            
                            <input type="hidden" value="<?php echo $this->orderId?>" name="order_id" />
                            <table width="80%" border="1" cellpadding="10" cellspacing="0" bordercolor="#FFFFFF" bgcolor="#FCFCFC" class="STYLE2">
                              <tr>
                                <td width="37%" class="STYLE2"><div align="right">Country</div></td>
                                <td width="63%">                                 
                                    <div align="left">
                                      <select name="country_code" class="input2">
                                        <option value="AU">Australia</option>
                                      	<option value="US">USA</option>
                                      	<option value="CN">China</option>
                                      	
                                      </select>
                                    </div>
                                </td>
                              </tr>
                              <tr>
                                <td width="37%" class="STYLE2"><div align="right">Credit Card Type</div></td>
                                <td width="63%">                                 
                                    <div align="left">
                                    	<select name="credit_card_type" class="input2">
	                                        <option value="Visa">Visa</option>
	                                      	<option value="MasterCard">MasterCard</option>
                                      	</select>
                                    </div>
                                </td>
                              </tr>
                              <tr>
                                <td class="STYLE2"><div align="right">Credit Card Numeber </div></td>
                                <td><div align="left">
                                  <input name="credit_card_number" id="credit_card_number" type="text" class="input2" />
                                </div></td>
                              </tr>
                              <tr>
                                <td class="STYLE2"><div align="right">CVV</div></td>
                                <td><div align="left">
                                  <input name="cvv2" id="cvv2" type="text" class="input2" />
                                </div></td>
                              </tr>
                              <tr>
                                 <td class="STYLE2"><div align="right">Expiration Date </div></td>
                              	 <td><div align="left">
                                  <input name="expiration_date" id="expiration_date" type="text" class="input2" />
                                </div></td>
                              </tr>
                              <tr>
                                <td class="STYLE2"><div align="right">Frist Name </div></td>
                                <td><div align="left">
                                  <input name="first_name" id="first_name" type="text" class="input2" />
                                </div></td>
                              </tr>
                              <tr>
                                <td class="STYLE2"><div align="right">Last Name </div></td>
                                <td><div align="left">
                                  <input name="last_name" id="last_name" type="text" class="input2" />
                                </div></td>
                              </tr>
                              
                              <tr>
                                <td class="STYLE2"><div align="right">Street</div></td>
                                <td><div align="left">
                                  <input name="street" id="street" type="text" class="input1" />
                                </div></td>
                              </tr>
                              <tr>
                                <td class="STYLE2"><div align="right">City</div></td>
                                <td><div align="left">
                                  <input name="city" id="city" type="text" class="input2" />
                                </div></td>
                              </tr>
                              <tr>
                                <td class="STYLE2"><div align="right">State</div></td>
                                <td><div align="left">
                                  <input name="state" id="state" type="text" class="input2" />
                                </div></td>
                              </tr>
                              <tr>
                                <td class="STYLE2"><div align="right">Zip</div></td>
                                <td><div align="left">
                                  <input name="zip" id="zip" type="text" class="input2" />
                                </div></td>
                              </tr>
                           
                              <tr>
                                <td class="STYLE2"><div align="right">
                                  
                                </div></td>
                                <td><div align="left">
                                  <input type="submit" name="Submit2" value="pay" />
                                </div></td>
                              </tr>
                            </table>
                                  </form>
                          </div></td>
                        </tr>
                    </table></td>
                  </tr>
                </table>
                <!-- InstanceEndEditable --></td>
                
                
                
                <script>
                	$("#expiration_date").datepicker({ dateFormat: 'dd-mm-yy' });
		
                	function checkForm(){

                		

                		var isEmpty = rocknoon.validate.is_empty( $("#credit_card_number").val() );
                		if( isEmpty ){
                			alert( "please fill in your credit card number" );
                			return false;
                		}

                		var isEmpty = rocknoon.validate.is_empty( $("#cvv2").val() );
                		if( isEmpty ){
                			alert( "please fill in your Card Verification Value" );
                			return false;
                		}

                		var isEmpty = rocknoon.validate.is_empty( $("#expiration_date").val() );
                		if( isEmpty ){
                			alert( "please select expiration date" );
                			return false;
                		}

                		var isEmpty = rocknoon.validate.is_empty( $("#first_name").val() );
                		if( isEmpty ){
                			alert( "please fill in your first name" );
                			return false;
                		}

                		var isEmpty = rocknoon.validate.is_empty( $("#last_name").val() );
                		if( isEmpty ){
                			alert( "please fill in your last name" );
                			return false;
                		}

                		var isEmpty = rocknoon.validate.is_empty( $("#street").val() );
                		if( isEmpty ){
                			alert( "please fill in street" );
                			return false;
                		}

                		var isEmpty = rocknoon.validate.is_empty( $("#city").val() );
                		if( isEmpty ){
                			alert( "please fill in city" );
                			return false;
                		}

                		var isEmpty = rocknoon.validate.is_empty( $("#state").val() );
                		if( isEmpty ){
                			alert( "please fill in state" );
                			return false;
                		}

                		var isEmpty = rocknoon.validate.is_empty( $("#zip").val() );
                		if( isEmpty ){
                			alert( "please fill in zip" );
                			return false;
                		}

                		
                		
                		
                		return true;
                		
                	}
                	
                </script>