<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><!-- InstanceBegin template="/Templates/t1.dwt" codeOutsideHTMLIsLocked="false" -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<script type="text/javascript">
//<!--
	/*
	 * global var
	 */
	var __BASE_URL__  = '<?php echo $this->baseUrl()?>';
	var __IS_LOGIN__  = <?php echo intval($this->isLogin)?>;

	
	
//--> 
</script>


<?php 
echo $this->headScript();
echo $this->headStyle();
echo $this->headLink(); 
echo $this->headTitle();
?>


<?php
//if use compress js file
if( WeFlex_Application::GetInstance()->config->js->compress ){
	echo '<script type="text/javascript" src="'.$this->baseUrl().WeFlex_Application::GetInstance()->config->js->dir.'"></script> ';
}
?>

<link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl()?>/css/style.css" />



</head>


<body>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td bgcolor="#A72424">
    <div align="center">
      <table width="1024" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td><table width="1024" height="130" border="0" cellpadding="0" cellspacing="0">
            <tr>
              <td width="263"><div align="left"><img src="<?php echo $this->baseUrl()?>/images/logo.gif" width="210" height="70" /></div></td>
              <td width="761"><table width="100%" height="130" border="0" cellpadding="0" cellspacing="0">
                <tr>
                  <td><div align="right"><!-- InstanceBeginEditable name="EditRegion2" --><!-- InstanceEndEditable --></div></td>
                </tr>
                <tr>
                  <td height="45" valign="bottom"><div align="center">
                    <table width="100" border="0" align="left" cellpadding="5" cellspacing="0">
                      <tr>
                        <td width="6%"><div align="center">
                            <table width="50" border="0" cellpadding="0" cellspacing="0" class="topmenu">
                              <tr>
                                <td ><div align="center"><a href="<?php echo $this->url(array("action" => "index" , "controller" => "index"), 'default', true);?>">Home</a></div></td>
                              </tr>
                            </table>
                        </div></td>
                        <td width="34%" ><div align="center">
                          <table width="210" border="0" cellpadding="0" cellspacing="0" class="topmenu">
                            <tr>
                              <td><a href="<?php echo $this->url(array("action" => "index" , "controller" => "courses"), 'default', true);?>">Veterinary Acupuncture Program</a></td>
                            </tr>
                          </table>
                        </div></td>
                        <td width="9%" ><div align="center">
                          <table width="50" border="0" cellpadding="0" cellspacing="0" class="topmenu">
                            <tr>
                              <td><a href="<?php echo $this->url(array(), 'faculty', true);?>">Faculty</a></td>
                            </tr>
                          </table>
                        </div></td>
                        <td width="16%"><div align="center">
                          <table width="50" border="0" cellpadding="0" cellspacing="0" class="topmenu">
                            <tr>
                              <td><a href="<?php echo $this->url(array(), 'certification', true);?>">Certification</a></td>
                            </tr>
                          </table>
                        </div></td>
                        <td width="20%" ><div align="center">
                          <table width="124" border="0" cellpadding="0" cellspacing="0" class="topmenu">
                            <tr>
                              <td width="80"><div align="center"><a target="_blank" href="http://online.tcvm.com/" >Remote Learning</a></div></td>
                            </tr>
                          </table>
                          <a href="#"></a><a href="#"></a></div></td>
                        <td width="15%" ><div align="center">
                          <table width="100" border="0" cellpadding="0" cellspacing="0" class="topmenu">
                            <tr>
                              <td><div align="center"><a href="<?php echo $this->url(array("action" => "register" , "controller" => "user"), 'default', true);?>">Registration</a></div></td>
                            </tr>
                          </table>
                        </div></td>
                      </tr>
                    </table>
                  </div></td>
                </tr>
                <tr>
                  <td valign="bottom"><div align="right"><img src="<?php echo $this->baseUrl()?>/images/tel.gif" width="183" height="21" /></div></td>
                </tr>
              </table></td>
            </tr>
          </table></td>
        </tr>
      </table>
    </div></td>
  </tr>
  <tr>
    <td bgcolor="#595959"><div align="center"> 
      <table width="1024" height="500" border="0" cellpadding="5" cellspacing="0" bgcolor="#FFFFFF">
        <tr>
          <td valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="5">
            <tr>
              <td valign="top"><table width="220" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td width="5%" rowspan="2" valign="top"><img src="<?php echo $this->baseUrl() ?>/images/dot.gif" width="9" height="9" /></td>
                  <td valign="top">
                    <div align="right">
                      <table width="192" border="0" align="right" cellpadding="1" cellspacing="0" bgcolor="#CCCCCC">
                            <tr>
                              <td><table width="100%" border="0" align="right" cellpadding="2" cellspacing="0" bgcolor="#FFFFFF">
                                <tr>
                                  <td><div align="left">
                                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                          <tr>
                                            <td width="11%"><div align="center"><img src="<?php echo $this->baseUrl() ?>/images/arrow.gif" width="3" height="5" /></div></td>
                                            <td width="89%"><div align="left"><span class="STYLE2"><a href="<?php echo $this->url(array("action" => "under-construction" , "controller" => "index"), 'default', true);?>">Acupuncture</a> </span></div></td>
                                          </tr>
                                          </table>
                                  </div></td>
                                </tr>
                                <tr>
                                  <td><div align="left">
                                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                          <tr>
                                            <td width="11%"><div align="center"><img src="<?php echo $this->baseUrl() ?>/images/arrow.gif" width="3" height="5" /></div></td>
                                            <td width="89%"><div align="left"><span class="STYLE2"><a href="<?php echo $this->url(array("action" => "under-construction" , "controller" => "index"), 'default', true);?>">Herbal Medicine </a> </span></div></td>
                                          </tr>
                                          </table>
                                  </div></td>
                                </tr>
                                <tr>
                                  <td><div align="left">
                                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                          <tr>
                                            <td width="11%"><div align="center"><img src="<?php echo $this->baseUrl() ?>/images/arrow.gif" width="3" height="5" /></div></td>
                                            <td width="89%"><div align="left"><span class="STYLE2"><a href="<?php echo $this->url(array("action" => "under-construction" , "controller" => "index"), 'default', true);?>">TCVM Food Therapy </a></span></div></td>
                                          </tr>
                                          </table>
                                  </div></td>
                                </tr>
                                <tr>
                                  <td><div align="left">
                                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                          <tr>
                                            <td width="11%"><div align="center"><img src="<?php echo $this->baseUrl() ?>/images/arrow.gif" width="3" height="5" /></div></td>
                                            <td width="89%"><div align="left"><span class="STYLE2"><a href="<?php echo $this->url(array("action" => "under-construction" , "controller" => "index"), 'default', true);?>">TCVM Tui Na </a></span></div></td>
                                          </tr>
                                          </table>
                                  </div></td>
                                </tr>
                                <tr>
                                  <td><div align="left">
                                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                          <tr>
                                            <td width="11%"><div align="center"><img src="<?php echo $this->baseUrl() ?>/images/arrow.gif" width="3" height="5" /></div></td>
                                            <td width="89%"><div align="left"><span class="STYLE2"><a href="<?php echo $this->url(array("action" => "under-construction" , "controller" => "index"), 'default', true);?>">Lecturers</a> </span></div></td>
                                          </tr>
                                          </table>
                                  </div></td>
                                </tr>
                                <tr>
                                  <td><div align="left">
                                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                          <tr>
                                            <td width="11%"><div align="center"><img src="<?php echo $this->baseUrl() ?>/images/arrow.gif" width="3" height="5" /></div></td>
                                            <td width="89%"><div align="left"><span class="STYLE2"><a href="<?php echo $this->url(array("action" => "under-construction" , "controller" => "index"), 'default', true);?>">Chi Institute Homepage</a></span></div></td>
                                          </tr>
                                          </table>
                                  </div></td>
                                </tr>
                                <tr>
                                  <td><div align="left">
                                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                          <tr>
                                            <td width="11%"><div align="center"><img src="<?php echo $this->baseUrl() ?>/images/arrow.gif" width="3" height="5" /></div></td>
                                            <td width="89%"><div align="left"><span class="STYLE2"><a href="<?php echo $this->url(array("action" => "under-construction" , "controller" => "index"), 'default', true);?>">AATCVM and AJTCVM </a> </span></div></td>
                                          </tr>
                                          </table>
                                  </div></td>
                                </tr>
                                <tr>
                                  <td><div align="left">
                                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                          <tr>
                                            <td width="11%"><div align="center"><img src="<?php echo $this->baseUrl() ?>/images/arrow.gif" width="3" height="5" /></div></td>
                                            <td width="89%"><div align="left"><span class="STYLE2"><a href="<?php echo $this->url(array("action" => "under-construction" , "controller" => "index"), 'default', true);?>">Jing-Tang herbal website </a></span></div></td>
                                          </tr>
                                          </table>
                                  </div></td>
                                </tr>
                                <tr>
                                  <td><div align="left">
                                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                          <tr>
                                            <td width="11%"><div align="center"><img src="<?php echo $this->baseUrl() ?>/images/arrow.gif" width="3" height="5" /></div></td>
                                            <td width="89%"><div align="left" class="STYLE2"><a href="<?php echo $this->url(array("action" => "under-construction" , "controller" => "index"), 'default', true);?>">Payment</a></div></td>
                                          </tr>
                                          </table>
                                  </div></td>
                                </tr>
                                <tr>
                                  <td><div align="left">
                                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                          <tr>
                                            <td width="11%"><div align="center"><img src="<?php echo $this->baseUrl() ?>/images/arrow.gif" width="3" height="5" /></div></td>
                                            <td width="89%"><div align="left"><span class="STYLE2"><a href="<?php echo $this->url(array("action" => "order" , "controller" => "user"), 'default', true);?>">Purchase Records</a></span></div></td>
                                          </tr>
                                          </table>
                                  </div></td>
                                </tr>
                                <tr>
                                  <td>&nbsp;</td>
                                </tr>
                                <tr>
                                  <td>&nbsp;</td>
                                </tr>
                                <tr>
                                  <td>&nbsp;</td>
                                </tr>
                              </table></td>
                            </tr>
                            </table>
                    </div></td></tr>
                <tr>
                  <td valign="top"><img src="<?php echo $this->baseUrl() ?>/images/transparent.gif" width="5" height="5" /></td>
                </tr>
                <tr>
                  <td valign="top"><img src="<?php echo $this->baseUrl() ?>/images/dot.gif" width="9" height="9" /></td>
                  <td><div align="right">
                    <table width="90%" border="0" align="right" cellpadding="0" cellspacing="0" bgcolor="#e8e3da">
                      <tr>
                        <td><div align="center">
                            <table width="100%" border="0" cellspacing="0" cellpadding="8">
                              <tr>
                                <td><div align="left" class="STYLE3">Our Staff </div></td>
                              </tr>
                              <tr>
                                <td><img src="<?php echo $this->baseUrl() ?>/images/photo.jpg" width="177" height="68" /></td>
                              </tr>
                              <tr>
                                <td><div align="left"><span class="STYLE4">Meet Dr. </span><span class="STYLE4">Ferguson</span></div></td>
                              </tr>
                              <tr>
                                <td class="STYLE2"><div align="left">Dr. Bruce Ferguson received his MS in Animal Behaviour in 1986 and his DVM in 1992 from the University of Florida. He studied with the International Veterinary Acupuncture Society in 1997 and began attending Chi Institute of Chinese Medicine</div></td>
                              </tr>
                              <tr>
                                <td><div align="right" class="STYLE2"><a href="<?php echo $this->url(array(), 'faculty', true);?>">more details&gt;</a> </div></td>
                              </tr>
                            </table>
                        </div></td>
                      </tr>
                    </table>
                  </div></td>
                </tr>
                
                <tr>
                  <td height="1">&nbsp;</td>
                  <td height="1"><img src="<?php echo $this->baseUrl() ?>/images/transparent.gif" width="5" height="5" /></td>
                </tr>
                <tr>
                  <td valign="top"><img src="<?php echo $this->baseUrl() ?>/images/dot.gif" width="9" height="9" /></td>
                  <td valign="top"><div align="right">
                    <table width="192" border="0" align="right" cellpadding="5" cellspacing="0" bgcolor="#faf9f7">
                      <tr>
                        <td><div align="left" class="STYLE3">Find a TCVM Practitioner</div></td>
                      </tr>
                      <tr>
                        <td class="STYLE2"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                            <tr>
                              <td width="74" class="STYLE3"><div align="right">By State</div></td>
                              <td width="51" height="27" valign="middle"><div align="left">
                                  <select name="select" size="1" class="input1">
                                    <option>Western Australia</option>
                                    <option>South Australia</option>
                                    <option>Victoria</option>
                                    <option>New South Wales</option>
                                    <option>Queensland</option>
                                    <option>Tasmania</option>
                                    <option>Northern Territory </option>
                                    <option>ACT</option>
                                  </select>
                              </div></td>
                              <td width="52" valign="middle"><img src="<?php echo $this->baseUrl() ?>/images/find.gif" width="24" height="19" /></td>
                            </tr>
                            <tr>
                              <td class="STYLE3"><div align="right">By Zip </div></td>
                              <td height="27" valign="middle"><div align="left">
                                  <input name="textfield" type="text" class="input1" size="10" />
                              </div></td>
                              <td height="27" valign="middle"><img src="<?php echo $this->baseUrl() ?>/images/find.gif" width="24" height="19" /></td>
                            </tr>
                            <tr>
                              <td class="STYLE3"><div align="right">Within</div></td>
                              <td height="27" colspan="2"><div align="left">
                                  <select name="select2" class="input1">
                                    <option>30miles</option>
                                    <option>AK</option>
                                  </select>
                              </div></td>
                            </tr>
                        </table></td>
                      </tr>
                      <tr>
                        <td bgcolor="#ebeae8"><div align="right" class="STYLE2">
                            <div align="left"><a href="http://www.acuvet.com.au/">Practitioner Referrels</a></div>
                        </div></td>
                      </tr>
                      <tr>
                        <td bgcolor="#ebeae8"><div align="left" class="STYLE2"><a href="outofau.html">Practitioners Out of AU</a></a></div></td>
                      </tr>
                    </table>
                  </div></td>
                </tr>
                <tr>
                  <td>&nbsp;</td>
                  <td valign="top"><img src="<?php echo $this->baseUrl() ?>/images/transparent.gif" width="5" height="5" /></td>
                </tr>
                <tr>
                  <td valign="top"><img src="<?php echo $this->baseUrl() ?>/images/dot.gif" width="9" height="9" /></td>
                  <td><table width="90%" border="0" align="right" cellpadding="0" cellspacing="0">
                    <tr>
                      <td class="STYLE3"><div align="left">Contact Us </div></td>
                    </tr>
                    <tr>
                      <td><div align="left"><span class="STYLE2">Bruce Ferguson DVM, MS <br />
                        P.O. Box 7100 <br />
                        Karawara, WA 6152 <br />
                        AUSTRALIA <br />
                        Phone: + 61 41525-8269 <br />
                        Email: <a href="mailto:naturalvet@earthlink.net">naturalvet@earthlink.net</a></span> <br />
                        <br />
                      </div></td>
                    </tr>
                  </table></td>
                </tr>
                <tr>
                  <td>&nbsp;</td>
                  <td>&nbsp;</td>
                </tr>
              </table></td>
              
            
              <?php echo $this->layout()->content ?>
              
            </tr>
          </table>  </td>
        </tr>
      </table>
    </div></td>
  </tr>
  <tr>
    <td height="62" bgcolor="#A72424"><div align="center" class="STYLE1"><a href="#">Copyright @ 2011  tcvm.com.au . All rights reserved.</a></div></td>
  </tr>
</table>

<map name="Map" id="Map">
  <area shape="rect" coords="897,62,992,91" href="<?php echo $this->url(array("action" => "register" , "controller" => "user"), 'default', true);?>" />
  <area shape="rect" coords="766,63,886,92" target="_blank" href="http://online.tcvm.com/" />
  <area shape="rect" coords="662,63,753,92" href="<?php echo $this->url(array(), 'certification', true);?>" />
  <area shape="rect" coords="585,63,654,92" href="<?php echo $this->url(array(), 'faculty', true);?>" />
  <area shape="rect" coords="359,62,578,91" href="<?php echo $this->url(array("action" => "index" , "controller" => "courses"), 'default', true);?>" />
  <area shape="rect" coords="293,62,351,91" href="<?php echo $this->url(array("action" => "index" , "controller" => "index"), 'default', true);?>" />
</map>
</body>
<!-- InstanceEnd --></html>
