			<td width="81%" align="center" valign="top"><!-- InstanceBeginEditable name="EditRegion1" -->
                <div align="center"></div>
                <table width="750" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td><p align="center" class="STYLE5">Confirm</p>
                      <form id="form1" name="form1" method="post" action="<?php echo $this->url(array("action" => "do-confirm" , "controller" => "cart"), 'default', true);?>">
                        <table width="80%" border="1" align="center" cellpadding="10" cellspacing="0" bordercolor="#FFFFFF" bgcolor="#FCFCFC" class="STYLE2">
                          
                          
                          <tr>
                            <td class="STYLE2"><div align="right">
                                <label>
                                <input type="submit" name="Submit" value="save" />
                                </label>
                            </div></td>
                            <td><div align="left">
                                <input type="submit" name="Submit2" value="cancel" />
                            </div></td>
                          </tr>
                        </table>
                                            </form>
                      <p>&nbsp;</p></td>
                  </tr>
                </table>
                <!-- InstanceEndEditable --></td>