			<td width="81%" align="center" valign="top"><!-- InstanceBeginEditable name="EditRegion1" -->
                <div align="center"></div>
                <table width="750" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td><p align="center" class="STYLE5">Shipping</p>
                      <form id="form1" name="form1" method="post" action="<?php echo $this->url(array("action" => "do-shipping" , "controller" => "cart"), 'default', true);?>">
                        <table width="80%" border="1" align="center" cellpadding="10" cellspacing="0" bordercolor="#FFFFFF" bgcolor="#FCFCFC" class="STYLE2">
                          <tr>
                            <td width="37%" class="STYLE2"><div align="right">Frist Name </div></td>
                            <td width="63%"><div align="left">
                                <input name="first_name" type="text" class="input2" />
                            </div></td>
                          </tr>
                          <tr>
                            <td class="STYLE2"><div align="right">Last Name </div></td>
                            <td><div align="left">
                                <input name="last_name" type="text" class="input2" />
                            </div></td>
                          </tr>
                          
                          <tr>
                            <td class="STYLE2"><div align="right">Mobile</div></td>
                            <td><div align="left"><span class="STYLE1">
                                <input name="mobile" type="text" class="input2" />
                            </span></div></td>
                          </tr>
                          
                          <tr>
                            <td class="STYLE2"><div align="right">
                                <label>
                                <input type="submit" name="Submit" value="save" />
                                </label>
                            </div></td>
                            <td><div align="left">
                                <input type="submit" name="Submit2" value="cancel" />
                            </div></td>
                          </tr>
                        </table>
                                            </form>
                      <p>&nbsp;</p></td>
                  </tr>
                </table>
                <!-- InstanceEndEditable --></td>