			<td width="81%" align="center" valign="top"><!-- InstanceBeginEditable name="EditRegion1" -->
                <div align="center"></div>
                <table width="750" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td><p align="center" class="STYLE5">Success</p>
                    
                    <table width="80%" border="0" align="center" cellpadding="0" cellspacing="0" style="margin-bottom:20px;" >
                          <tr>
                            <td>
                            <div class="SUCCESS">
                             The order has been successfully generated. you can enter into <a href="<?php echo $this->url(array("action" => "order" , "controller" => "user"), 'default', true);?>">order page </a> to view all of your orders, and then pay for them. If you have any question, please contact us.
							</div>
                    		</td>
                          </tr>
                    </table>
                    </td>
                  </tr>
                </table>
                <!-- InstanceEndEditable -->
            </td>