<div id="back_white_main">	

	<h2 class="cufon_h2">Order Management</h2>
		
		  
          <table class="backend_show_book" cellpadding="0" cellspacing="0" border="0" width="100%">
            <tr class="head">
              <th>ID</th>
              <th>User Email</th>
              <th>Total Price</th>
              <th>Time</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
            
            <?php foreach( $this->orders as $order ):?>
            <tr>
              <td><?php echo $order['id']?></td>
              <td><?php echo $order['email']?></td>
              <td><?php echo $order['total_price']?></td>
              <td><?php echo date( "Y-m-d" , $order['date_add'] );?></td>
              <td>
              						<?php switch( $order['status'] ):
                                  
                                  	 case TCVM_Order_Imple::STATUS_WAITTING_PAY:?>
                                    	Waitting For pay
                                  	<?php break;?>
                                  	
                                  	<?php case TCVM_Order_Imple::STATUS_CANCEL:?>
                                    	Cancel
                                  	<?php break;?>
                                  	
                                  	<?php case TCVM_Order_Imple::STATUS_SUCCESS:?>
                                    	Success
                                  	<?php break;?>
                                  	
                                  	<?php case TCVM_Order_Imple::STATUS_WAITTING_ELECTRONIC_TRANSFER:?>
                                    	Waitting for your electronic transfer
                                  	<?php break;?>
                                  	
                                  <?php endswitch;?>
             
              
              </td>
              <td>
              	<a href="<?php echo $this->url(array('controller' => 'order', 'action' => 'view', 'module' => 'admin' , "id" => $order['id']), "default" , true);?>">View Detail</a>
              </td>
            </tr>
            <?php endforeach;?>
            
		 </table>
		 <?php if($this->pagination):?>
			 <?php echo $this->pagination ?>
		 <?php endif;?>
		 
</div>


	
	
