<div id="back_white_main">	

	<h2 class="cufon_h2">Order Management</h2>
		
		  
          <table class="backend_show_book" cellpadding="0" cellspacing="0" border="0" width="100%">
            <tr class="head">
              <th>ID</th>
              <th>User</th>
              <th>Total Price</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
            
            <?php foreach( $this->orders as $order ):?>
            <tr>
              <td><?php echo $order['id']?></td>
              <td><?php echo $order['user_id']?></td>
              <td><?php echo $order['total_price']?></td>
              <td><?php echo $order['status']?></td>
              <td>
              	<a href="<?php echo $this->url(array('controller' => 'order', 'action' => 'view', 'module' => 'admin' , "id" => $order['id']), "default" , true);?>">View Detail</a>
              </td>
            </tr>
            <?php endforeach;?>
            
		 </table>
		 
</div>


	
	
