<div id="back_main">
		<h2 class="cufon_h2">Order View</h2>

		<form class="form" action="<?php echo $this->url(array(
				'controller' => 'order', 
				'action' => 'do-status', 
				'module' => 'admin'
				), null , true);?>" 
				method="post">
						
		<input type="hidden" value="<?php echo $this->order['id']?>" name="id" id="id" />
		
		
		<div>
		<label>Order Id:</label>
		<?php echo $this->order['id']?>
		</div>
		
		<div>
		<label>Total Price:</label>
		<?php echo $this->order['total_price']?>
		</div>
		
		<div>
		<label>Products:</label>
		<?php foreach($this->order['products'] as $product):?>
			<?php echo $product['name'] ?> &nbsp;&nbsp;  &nbsp;&nbsp; Price:<?php echo $product['price'] ?><br/>
		<?php endforeach;?>
		</div>
			
		<div>
		<label>Status:</label>
		<select name="status" id="status">
			<option value="<?php echo TCVM_Order_Imple::STATUS_WAITTING_PAY?>">Waitting For Pay</option>
			<option value="<?php echo TCVM_Order_Imple::STATUS_WAITTING_ELECTRONIC_TRANSFER?>">Waitting For Electronic Transfer</option>
			<option value="<?php echo TCVM_Order_Imple::STATUS_CANCEL?>">Cancel</option>
			<option value="<?php echo TCVM_Order_Imple::STATUS_SUCCESS?>">Success</option>
		</select>
		</div>
		
		
		<!-- basic info -->
		<?php foreach( $this->order["cart_info"]["basic"] as $key => $value ):?>
		
		<div>
		<label><?php echo $key?>:<?php echo $value?></label>
		
		</div>
		<?php endforeach;?>
		
		<!-- profile info -->
		<div>
		<label>Biographical:<a href="<?php echo $this->baseUrl().$this->order["cart_info"]['profile']["biographical"]?>" target="_blank">view</a></label>
			
		</div>
		
		<div>
		<label>photo:<a href="<?php echo $this->baseUrl().$this->order["cart_info"]['profile']["photo"]?>" target="_blank">view</a></label>
			
		</div>
		

		

		<div class="for_align_right">
		<input type="submit" value="Submit" class="back_btn"/>
		</div>		

		</form>
		
</div>

<script>


	$("#status").val(<?php echo $this->order['status']?>);


	
</script>