
		
				<td width="81%" align="center" valign="top"><!-- InstanceBeginEditable name="EditRegion1" -->
                <div align="center"></div>
                <table width="750" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td><p align="center" class="STYLE5">Find Password</p>
                      <form id="form1" name="form1" method="post"  action="<?php echo $this->url( array("action"=> "post-find-password", "controller"=> "user" ) , "default" , true )?>">
                        <table width="80%" border="1" align="center" cellpadding="10" cellspacing="0" bordercolor="#FFFFFF" bgcolor="#FCFCFC" class="STYLE2">
                        
                          <tr>
                            <td class="STYLE2"><div align="right">Email Address</div></td>
                            <td><div align="left">
                                <input name="email" id="email" type="text" class="input2" />
                            </div></td>
                          </tr>

                          
                          <tr>
                            <td class="STYLE2"></td>
                            <td><div align="left">
                                <label>
                                <input type="submit" name="Submit" value="Find Password" />
                                </label>
                            </div></td>
                          </tr>
                        </table>
                      </form>
                      <p>&nbsp;</p></td>
                  </tr>
                </table>
                <!-- InstanceEndEditable --></td>
