			<td width="81%" align="center" valign="top"><!-- InstanceBeginEditable name="EditRegion1" -->
                <div align="center"></div>
                <table width="750" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td><p align="center" class="STYLE5">Sign in</p>
                      <form id="form1" name="form1" method="post" onsubmit="return checkForm();" action="<?php echo $this->url(array("action" => "do-login" , "controller" => "user"), 'default', true);?>">
                        <table width="80%" border="1" align="center" cellpadding="10" cellspacing="0" bordercolor="#FFFFFF" bgcolor="#FCFCFC" class="STYLE2">
                        
                          <tr>
                            <td class="STYLE2"><div align="right">Email Address</div></td>
                            <td><div align="left">
                                <input name="email" id="email" type="text" class="input2" />
                            </div></td>
                          </tr>
                          
                          <tr>
                            <td class="STYLE2"><div align="right">Password</div></td>
                            <td><div align="left">
                                <input name="password" id="password" type="password" class="input2" />
                            </div></td>
                          </tr>
                          
                          <tr>
                            <td class="STYLE2"></td>
                            <td><div align="left">
                               
                            	<a href="<?php echo $this->url(array("action" => "register" , "controller" => "user"), 'default', true);?>">sign up</a>
                            	&nbsp;&nbsp;&nbsp;<a href="<?php echo $this->url(array("action" => "find-password" , "controller" => "user"), 'default', true);?>">forget password</a>
                            </div></td>
                          </tr>
                          
                          
                          
                          <tr>
                            <td class="STYLE2"></td>
                            <td><div align="left">
                                <label>
                                <input type="submit" name="Submit" value="sign in" /> 
                                </label>
                            </div></td>
                          </tr>
                        </table>
                      </form>
                      <p>&nbsp;</p></td>
                  </tr>
                </table>
                <!-- InstanceEndEditable --></td>
                
                
<script>
	
</script>