			<td width="81%" align="center" valign="top"><!-- InstanceBeginEditable name="EditRegion1" -->
                <div align="center"></div>
                <table width="750" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td><div align="center">
                      <p class="STYLE5">Purchase Records</p>
                      <form id="form1" name="form1" method="post" action="">
                        <table width="100%" border="0" cellpadding="5" cellspacing="0" class="table2">
                          <tr>
                            <td width="3%">&nbsp;</td>
                            <td width="40%">&nbsp;</td>
                            <td width="7%">&nbsp;</td>
                            <td width="20%">&nbsp;</td>
                            <td width="14%">&nbsp;</td>
                            <td width="13%">&nbsp;</td>
                            <td width="3%">&nbsp;</td>
                          </tr>
                          <tr>
                            <td>&nbsp;</td>
                            <td class="underline2"><div align="left" class="STYLE4">Product Name </div></td>
                            <td class="underline2"><div align="left" class="STYLE4">Price</div></td>
                            <td class="underline2"><div align="left" class="STYLE4">Quantity</div></td>
                            <td class="underline2"><div align="left" class="STYLE4">Amount</div></td>
                            <td class="underline2"><div align="left" class="STYLE4">Status</div></td>
                            <td class="STYLE4">&nbsp;</td>
                          </tr>
                          
                          <?php foreach( $this->orders as $order ):?>
                          <tr>
                            <td>&nbsp;</td>
                            <td class="orderid">Order ID:<?php echo $order['id']?></td>
                            <td class="orderid"><div align="left">Date:</div></td>
                            <td class="orderid">2011-7-28</td>
                            <td class="orderid">&nbsp;</td>
                            <td class="orderid">&nbsp;</td>
                            <td>&nbsp;</td>
                          </tr>
                          
                          <?php foreach( $order['products'] as $key => $product ):?>
                          <tr>
                            <td>&nbsp;</td>
                            <td class="underline"><div align="left" class="STYLE2"><?php echo $product['name']?></div></td>
                            <td class="underline"><div align="left" class="STYLE2"><?php echo $product['price']?></div></td>
                            <td valign="middle" class="underline"><label>
                              <div align="left">
                                <select name="select3" size="1" class="input3">
                                  <option>1</option>
                                  <option>2</option>
                                </select>
                                </label>
                              </div></td>
                            <td class="underline"><div align="left" class="STYLE4">2090</div></td>
                            
                            
                            <?php if( $key == 0 ):?>
                            <td rowspan="3" valign="top" class="underline">
                                <label></label>
                                
                                  <div align="left">
                                    <input name="Submit3" type="button" onclick="doPayment(<?php echo $order['id']?>);" class="redbutton2" value="Pay Now" />
                                  </div>                                  
                                  <div align="left" class="STYLE2"></div>
                            </td>
                            <td class="STYLE2">&nbsp;</td>
                            <?php endif;?>
                            
                          </tr>
                          
                          <?php endforeach;?>
                          
                          
                          
                         <?php endforeach;?>
                            
                            
                          <tr>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                          </tr>
                          <tr>
                            <td>&nbsp;</td>
                            <td class="underline">&nbsp;</td>
                            <td class="underline">&nbsp;</td>
                            <td class="underline2">&nbsp;</td>
                            <td class="underline2">&nbsp;</td>
                            <td class="underline"><div align="left"></div></td>
                            <td>&nbsp;</td>
                          </tr>
                          <tr>
                            <td>&nbsp;</td>
                            <td class="STYLE2"><div align="left">&lt;Previous page </div></td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td><label></label></td>
                            <td class="STYLE2"><div align="right">next page&gt; </div></td>
                            <td>&nbsp;</td>
                          </tr>
                        </table>
                            </form>
                      <p class="STYLE5">&nbsp;</p>
                    </div></td>
                  </tr>
                </table>
                <!-- InstanceEndEditable --></td>
                
<script>
function doPayment(orderId){
	location.href="<?php echo $this->url(array("action" => "payment" , "controller" => "pay"), 'default', true);?>" + "/order_id/" + orderId;
}
</script>