			<td width="81%" align="center" valign="top"><!-- InstanceBeginEditable name="EditRegion1" -->
                <div align="center"></div>
                <table width="750" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td><p align="center" class="STYLE5">Sign up</p>
                      <form id="form1" name="form1" method="post" onsubmit="return checkForm();" action="<?php echo $this->url(array("action" => "do-register" , "controller" => "user"), 'default', true);?>">
                        <table width="80%" border="1" align="center" cellpadding="10" cellspacing="0" bordercolor="#FFFFFF" bgcolor="#FCFCFC" class="STYLE2">
                        
                          <tr>
                            <td class="STYLE2"><div align="right">Email Address *</div></td>
                            <td><div align="left">
                                <input name="email" id="email" type="text" class="input2" />
                            </div></td>
                          </tr>
                          
                          <tr>
                            <td class="STYLE2"><div align="right">Password *</div></td>
                            <td><div align="left">
                                <input name="password" id="password" type="password" class="input2" />
                            </div></td>
                          </tr>
                          
                          <tr>
                            <td class="STYLE2"><div align="right">Re-type password *</div></td>
                            <td><div align="left">
                                <input name="retype_password" id="retype_password" type="password" class="input2" />
                            </div></td>
                          </tr>
                          
                          <tr>
                            <td width="37%" class="STYLE2"><div align="right">Frist Name </div></td>
                            <td width="63%"><div align="left">
                                <input name="first_name" type="text" class="input2" />
                            </div></td>
                          </tr>
                          
                          <tr>
                            <td class="STYLE2"><div align="right">Last Name </div></td>
                            <td><div align="left">
                                <input name="last_name" type="text" class="input2" />
                            </div></td>
                          </tr>
                          <tr>
                            <td class="STYLE2"><div align="right">Billing Address Line 1 </div></td>
                            <td><div align="left">
                                <input name="billing_address_1" type="text" class="input2" />
                            </div></td>
                          </tr>
                          <tr>
                            <td class="STYLE2"><div align="right">Billing Address Line 2 </div></td>
                            <td><div align="left">
                                <input name="billing_address_2" type="text" class="input2" />
                            </div></td>
                          </tr>
                          <tr>
                            <td class="STYLE2"><div align="right">ZIP Code </div></td>
                            <td><div align="left">
                                <input name="zip_code" type="text" class="input1" />
                            </div></td>
                          </tr>
                          <tr>
                            <td class="STYLE2"><div align="right">City</div></td>
                            <td><div align="left">
                                <input name="city" type="text" class="input2" />
                            </div></td>
                          </tr>
                          <tr>
                            <td class="STYLE2"><div align="right">State</div></td>
                            <td><div align="left">
                                <input name="state" type="text" class="input1" />
                            </div></td>
                          </tr>
                          <tr>
                            <td class="STYLE2"><div align="right">Tel</div></td>
                            <td><div align="left" class="STYLE2">
                                <input name="telephone" type="text" class="input2" />
                              e.g.555-555-5555</div></td>
                          </tr>
                          <tr>
                            <td class="STYLE2"><div align="right">Mobile</div></td>
                            <td><div align="left"><span class="STYLE1">
                                <input name="mobile" type="text" class="input2" />
                            </span></div></td>
                          </tr>
                          
                          <tr>
                            <td class="STYLE2"></td>
                            <td><div align="left">
                                <label>
                                <input type="submit" name="Submit" value="sign up" />
                                </label>
                            </div></td>
                          </tr>
                        </table>
                      </form>
                      <p>&nbsp;</p></td>
                  </tr>
                </table>
                <!-- InstanceEndEditable --></td>
                
                
<script>
	function checkForm(){

		var isEmail = rocknoon.validate.is_email( $("#email").val() );
		if( !isEmail ){
			alert( "sorry, the email address is not correct." )
			return false;
		}

		var isEmpty = rocknoon.validate.is_empty( $("#password").val() );
		if( isEmpty ){
			alert( "please fill in a password" );
			return false;
		}

		var isSame = rocknoon.validate.is_same( $("#password").val(), $("#retype_password").val() );
		if( !isSame ){
			alert( "The passwords you type twice are not same" );
			return false;
		}
		
		return true;
		
	}
</script>