<td width="81%" align="center" valign="top"><!-- InstanceBeginEditable name="EditRegion1" -->
                <div align="center"></div>
                <table width="750" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td><p>&nbsp;</p>
                      <p class="STYLE5" align="center" style='margin-top:9.0pt;margin-right:0cm;
  margin-bottom:9.0pt;margin-left:0cm;text-align:center'><b style='mso-bidi-font-weight:
  normal'><span style='font-size:14.0pt' lang="EN-US" xml:lang="EN-US">Chi Institute Australia
                        2012 Small Animal Acupuncture Program
                              <o:p></o:p>
                      </span></b></p>
                      <p class="STYLE5" align="center" style='margin-top:6.0pt;margin-right:0cm;
  margin-bottom:6.0pt;margin-left:0cm;text-align:center'><b style='mso-bidi-font-weight:
  normal'><span style='font-size:14.0pt' lang="EN-US" xml:lang="EN-US">Class Registration
                        </span></b></p>
                      <form onsubmit="return checkForm();" id="form1" name="form1" method="post" action="<?php echo $this->url(array("action" => "post-basic" , "controller" => "registration"), 'default', true);?>">
                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                          <tr>
                            <td><div align="left">
                              <p style="margin-top:0cm;margin-right:0cm;margin-bottom:3.0pt;
  margin-left:6.0pt;text-indent:-6.0pt">&nbsp;</p>
                              <p style="margin-top:0cm;margin-right:0cm;margin-bottom:3.0pt;
  margin-left:6.0pt;text-indent:-6.0pt"><span class="STYLE3"><b style='mso-bidi-font-weight:normal'><span style='font-size:10.0pt' lang="EN-US" xml:lang="EN-US">STEP 1:
                                Check courses previously attended.<span style='mso-spacerun:yes'>&nbsp; </span><span style="color:red">If none, leave this part as empty.</span></span></b></span></p>
                            </div></td>
                            </tr>
                          <tr>
                            <td><table width="100%" border="1" align="center" cellpadding="10" cellspacing="0" bordercolor="#FFFFFF" bgcolor="#FCFCFC" class="STYLE2">
                              <tr>
                                <td width="22%" class="STYLE2"><div align="right">Veterinary Acupuncture:</div></td>
                                <td width="78%"><div align="left">
                                  <table width="100%" border="0" cellspacing="5" cellpadding="0">
                                    <tr>
                                      <td width="22%"><div align="left">
                                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                          <tr>
                                            <td width="21%"><input type="checkbox" name="veterinary_acupuncture[]" <?php if( in_array( "small_animal",  $this->cartInfo['basic']['veterinary_acupuncture']) ) echo "checked"?> value="small_animal" /></td>
                                            <td width="79%">Small Animal</td>
                                          </tr>
                                        </table>
                                      </div></td>
                                      <td width="11%"><div align="left">
                                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                          <tr>
                                            <td width="15%"><input type="checkbox" name="veterinary_acupuncture[]" <?php if( in_array( "equine",  $this->cartInfo['basic']['veterinary_acupuncture']) ) echo "checked"?> value="equine" /></td>
                                            <td width="85%"> Equine</td>
                                          </tr>
                                        </table>
                                      </div></td>
                                      <td width="11%"><div align="left">
                                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                          <tr>
                                            <td width="15%"><input type="checkbox" name="veterinary_acupuncture[]" <?php if( in_array( "mixed",  $this->cartInfo['basic']['veterinary_acupuncture']) ) echo "checked"?> value="mixed" /></td>
                                            <td width="85%">Mixed</td>
                                          </tr>
                                        </table>
                                      </div></td>
                                      <td width="30%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                        <tr>
                                          <td width="15%">Where</td>
                                          <td width="85%"><input name="where" value="<?php if( isset( $this->cartInfo['basic']['where']) ) echo $this->cartInfo['basic']['where']?>" type="text" class="input1" /></td>
                                        </tr>
                                      </table></td>
                                      <td width="26%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                        <tr>
                                          <td width="15%">When</td>
                                          <td><input name="when" type="text" value="<?php if( isset( $this->cartInfo['basic']['when']) ) echo $this->cartInfo['basic']['when']?>" class="input1" /></td>
                                        </tr>
                                      </table></td>
                                    </tr>
                                  </table>
                                </div></td>
                              </tr>
                              <tr>
                                <td class="STYLE2"><div align="right">TCVM Clinical Approach /  Herbology:</div></td>
                                <td><div align="left">
                                  <table width="100%" border="0" cellspacing="5" cellpadding="0">
                                    <tr>
                                      <td width="20%"><div align="left">
                                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                          <tr>
                                            <td width="15%"><input type="checkbox" name="tcvm_clinical_approach[]" <?php if( in_array( "HT/LU",  $this->cartInfo['basic']['tcvm_clinical_approach']) ) echo "checked"?> value="HT/LU" /></td>
                                            <td width="85%">HT/LU</td>
                                          </tr>
                                        </table>
                                      </div></td>
                                      <td width="20%"><div align="left">
                                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                          <tr>
                                            <td width="15%"><input type="checkbox" name="tcvm_clinical_approach[]" <?php if( in_array( "SP/ST",  $this->cartInfo['basic']['tcvm_clinical_approach']) ) echo "checked"?> value="SP/ST" /></td>
                                            <td width="85%">SP/ST</td>
                                          </tr>
                                        </table>
                                      </div></td>
                                      <td width="20%"><div align="left">
                                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                          <tr>
                                            <td width="15%"><input type="checkbox" name="tcvm_clinical_approach[]" <?php if( in_array( "Liver/Endo",  $this->cartInfo['basic']['tcvm_clinical_approach']) ) echo "checked"?> value="Liver/Endo" /></td>
                                            <td width="85%">Liver/Endo</td>
                                          </tr>
                                        </table>
                                      </div></td>
                                      <td width="20%"><div align="left">
                                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                          <tr>
                                            <td width="15%"><input type="checkbox" name="tcvm_clinical_approach[]" <?php if( in_array( "Kid/Geri",  $this->cartInfo['basic']['tcvm_clinical_approach']) ) echo "checked"?> value="Kid/Geri" /></td>
                                            <td width="85%">Kid/Geri</td>
                                          </tr>
                                        </table>
                                      </div></td>
                                      <td width="20%"><div align="left">
                                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                          <tr>
                                            <td width="15%"><input type="checkbox" name="tcvm_clinical_approach[]" <?php if( in_array( "Derma/Immu",  $this->cartInfo['basic']['tcvm_clinical_approach']) ) echo "checked"?> value="Derma/Immu" /></td>
                                            <td width="85%">Derma/Immu</td>
                                          </tr>
                                        </table>
                                      </div></td>
                                       
                                   
                                    </tr>
                                  </table>
                                </div></td>
                              </tr>
                              <tr>
                                <td class="STYLE2"><div align="right">Advanced Programs:</div></td>
                                <td><div align="left">
                                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                    <tr>
                                      <td width="33%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                        <tr>
                                          <td width="15%"><input type="checkbox" name="advanced_programs[]" <?php if( in_array( "Certified Veterinary Tui-na",  $this->cartInfo['basic']['advanced_programs']) ) echo "checked"?> value="Certified Veterinary Tui-na" /></td>
                                          <td width="85%">Certified Veterinary Tui-na</td>
                                        </tr>
                                      </table></td>
                                      <td width="33%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                        <tr>
                                          <td width="15%"><input type="checkbox" name="advanced_programs[]" <?php if( in_array( "TCVM  Annual Conference",  $this->cartInfo['basic']['advanced_programs']) ) echo "checked"?> value="TCVM  Annual Conference" /></td>
                                          <td width="85%">TCVM  Annual Conference</td>
                                        </tr>
                                      </table></td>
                                      <td width="33%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                        <tr>
                                          <td width="15%"><input type="checkbox" name="advanced_programs[]" <?php if( in_array( "Tongue/Pulse Diagnosis &amp; Classical Points",  $this->cartInfo['basic']['advanced_programs']) ) echo "checked"?> value="Tongue/Pulse Diagnosis &amp; Classical Points" /></td>
                                          <td width="85%">Tongue/Pulse Diagnosis &amp; Classical Points</td>
                                        </tr>
                                      </table></td>
                                      
                          
                                      </tr>
                                  </table>
                                </div></td>
                              </tr>

                              
                            </table></td>
                            </tr>
                          <tr>
                            <td><div align="left"><span class="STYLE10"><strong>STEP 2:Contact Information/Preferred Mailing  Address. Print or type all information clearly. <span style="color:red">The red ones are mandatory.</span></strong></span></div></td>
                            </tr>
                          <tr>
                            <td><table width="100%" border="1" align="center" cellpadding="10" cellspacing="0" bordercolor="#FFFFFF" bgcolor="#FCFCFC" class="STYLE2">
                              <tr>
                                <td width="14%" class="STYLE2"><div align="right">Name</div></td>
                                <td width="86%"><div align="left">
                                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                    <tr>
                                      <td width="33%"><div align="left">
                                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                            <tr>
                                              <td width="35%"><div align="right"><span style="color:red">First Name:</span> </div></td>
                                              <td width="65%"><div align="left">
                                                <input name="first_name" id="first_name" value="<?php if( isset( $this->cartInfo['basic']['first_name']) ) echo $this->cartInfo['basic']['first_name']?>" type="text" class="input1" />
                                              </div></td>
                                            </tr>
                                                                              </table>
                                      </div></td>
                                      <td width="33%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                        <tr>
                                          <td width="45%"><div align="right"><span style="color:red">Middle Name:</span></div></td>
                                          <td width="55%"><input name="middle_name" id="middle_name" value="<?php if( isset( $this->cartInfo['basic']['middle_name']) ) echo $this->cartInfo['basic']['first_name']?>" type="text" class="input1" /></td>
                                        </tr>
                                      </table></td>
                                      <td width="33%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                        <tr>
                                          <td width="46%"><div align="right"><span style="color:red">Last Name:</span></div></td>
                                          <td width="54%"><input name="last_name" id="last_name" value="<?php if( isset( $this->cartInfo['basic']['last_name']) ) echo $this->cartInfo['basic']['last_name']?>" type="text" class="input1" /></td>
                                        </tr>
                                      </table></td>
                                    </tr>
                                  </table>
                                </div></td>
                              </tr>
                              <tr>
                                <td class="STYLE2"><div align="right">Title</div>                                  <div align="left"></div></td>
                                <td class="STYLE2"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                  <tr>
                                    <td width="33%"><div align="left">
                                      <input name="title" value="<?php if( isset( $this->cartInfo['basic']['title']) ) echo $this->cartInfo['basic']['title']?>" type="text" class="input1" />
                                    </div></td>
                                    <td width="33%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                      <tr>
                                        <td width="45%"><div align="right">Nickname:</div></td>
                                        <td width="55%"><input name="nick_name" value="<?php if( isset( $this->cartInfo['basic']['nick_name']) ) echo $this->cartInfo['basic']['nick_name']?>" type="text" class="input1" /></td>
                                      </tr>
                                    </table></td>
                                    <td width="33%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                      <tr>
                                        <td width="45%"><div align="right">License#:</div></td>
                                        <td width="55%"><input name="license" value="<?php if( isset( $this->cartInfo['basic']['license']) ) echo $this->cartInfo['basic']['license']?>" type="text" class="input1" /></td>
                                      </tr>
                                    </table></td>
                                  </tr>
                                </table></td>
                              </tr>
                              <tr>
                                <td class="STYLE2"><div align="right">Business</div></td>
                                <td><div align="left">
                                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                      <tr>
                                        <td width="33%"><input name="business" value="<?php if( isset( $this->cartInfo['basic']['business']) ) echo $this->cartInfo['basic']['business']?>" type="text" class="input1" /></td>
                                        <td width="15%"><div align="right">Practice</div></td>
                                        <td width="52%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                          <tr>
                                            <td width="25%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                              <tr>
                                                <td width="15%"><input type="checkbox" name="practice[]" <?php if( in_array( "SA",  $this->cartInfo['basic']['practice']) ) echo "checked"?>  value="SA" /></td>
                                                <td width="85%">SA</td>
                                              </tr>
                                            </table></td>
                                            <td width="25%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                              <tr>
                                                <td width="15%"><input type="checkbox" name="practice[]" <?php if( in_array( "EQ",  $this->cartInfo['basic']['practice']) ) echo "checked"?>  value="EQ" /></td>
                                                <td width="85%">EQ</td>
                                              </tr>
                                            </table></td>
                                            
                                        
                                            
                                          </tr>
                                        </table></td>
                                      </tr>
                                    </table>
                                </div></td>
                              </tr>
                              <tr>
                                <td rowspan="2" class="STYLE2"><div align="right">Address (W) </div></td>
                                <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                  <tr>
                                    <td width="14%">Street Address:</td>
                                    <td width="86%"><div align="left">
                                      <input name="street_1" value="<?php if( isset( $this->cartInfo['basic']['street_1']) ) echo $this->cartInfo['basic']['street_1']?>" type="text" class="input1" />
                                    </div></td>
                                  </tr>
                                </table></td>
                              </tr>
                              <tr>
                                <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                  <tr>
                                    <td width="25%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                      <tr>
                                        <td><div align="right">City:</div></td>
                                        <td><label>
                                          <div align="left">
                                            <input name="city_1" value="<?php if( isset( $this->cartInfo['basic']['city_1']) ) echo $this->cartInfo['basic']['city_1']?>" type="text" class="input1" />
                                            </div>
                                        </label></td>
                                      </tr>
                                    </table></td>
                                    <td width="25%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                      <tr>
                                        <td><div align="right">State: </div></td>
                                        <td><label>
                                          <div align="left">
                                            <input name="state_1" value="<?php if( isset( $this->cartInfo['basic']['state_1']) ) echo $this->cartInfo['basic']['state_1']?>" type="text" class="input1" />
                                            </div>
                                        </label></td>
                                      </tr>
                                    </table></td>
                                    <td width="25%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                      <tr>
                                        <td width="46%"><div align="right">Postal Code</div></td>
                                        <td width="54%"><div align="left">
                                          <input name="post_code_1" value="<?php if( isset( $this->cartInfo['basic']['post_code_1']) ) echo $this->cartInfo['basic']['post_code_1']?>" type="text" class="input1" />
                                        </div></td>
                                      </tr>
                                    </table></td>
                                    <td width="25%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                      <tr>
                                        <td><div align="right">Country: </div></td>
                                        <td><label>
                                          <div align="left">
                                            <input name="country_1" value="<?php if( isset( $this->cartInfo['basic']['country_1']) ) echo $this->cartInfo['basic']['country_1']?>" type="text" class="input1" />
                                            </div>
                                        </label></td>
                                      </tr>
                                    </table></td>
                                  </tr>
                                </table></td>
                              </tr>
                              <tr>
                                <td rowspan="2" class="STYLE2"><div align="right">Address (W) </div></td>
                                <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                  <tr>
                                    <td width="14%">Street Address:</td>
                                    <td width="86%"><div align="left">
                                      <input name="street_2" value="<?php if( isset( $this->cartInfo['basic']['street_2']) ) echo $this->cartInfo['basic']['street_2']?>" type="text" class="input1" />
                                    </div></td>
                                  </tr>
                                </table></td>
                              </tr>
                              <tr>
                                <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                  <tr>
                                    <td width="25%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                      <tr>
                                        <td><div align="right">City:</div></td>
                                        <td><label>
                                          <div align="left">
                                            <input name="city_2" value="<?php if( isset( $this->cartInfo['basic']['city_2']) ) echo $this->cartInfo['basic']['city_2']?>" type="text" class="input1" />
                                            </div>
                                        </label></td>
                                      </tr>
                                    </table></td>
                                    <td width="25%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                      <tr>
                                        <td><div align="right">State: </div></td>
                                        <td><label>
                                          <div align="left">
                                            <input name="state_2" value="<?php if( isset( $this->cartInfo['basic']['state_2']) ) echo $this->cartInfo['basic']['state_2']?>" type="text" class="input1" />
                                            </div>
                                        </label></td>
                                      </tr>
                                    </table></td>
                                    <td width="25%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                      <tr>
                                        <td width="46%"><div align="right">Postal Code</div></td>
                                        <td width="54%"><div align="left">
                                          <input name="post_code_2" value="<?php if( isset( $this->cartInfo['basic']['post_code_2']) ) echo $this->cartInfo['basic']['post_code_2']?>" type="text" class="input1" />
                                        </div></td>
                                      </tr>
                                    </table></td>
                                    <td width="25%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                      <tr>
                                        <td><div align="right">Country: </div></td>
                                        <td><label>
                                          <div align="left">
                                            <input name="country_2" value="<?php if( isset( $this->cartInfo['basic']['country_2']) ) echo $this->cartInfo['basic']['country_2']?>" type="text" class="input1" />
                                            </div>
                                        </label></td>
                                      </tr>
                                    </table></td>
                                  </tr>
                                </table></td>
                              </tr>
                              <tr>
                                <td class="STYLE2"><div align="right">Telephone</div></td>
                                <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                  <tr>
                                    <td width="33%"><table width="77%" border="0" cellspacing="0" cellpadding="0">
                                      <tr>
                                        <td width="15%"><div align="right"><span style="color:red">Work:</span></div></td>
                                        <td width="85%"><div align="left">
                                          <input name="work" id="work" value="<?php if( isset( $this->cartInfo['basic']['work']) ) echo $this->cartInfo['basic']['work']?>" type="text" class="input1" />
                                        </div></td>
                                      </tr>
                                    </table></td>
                                    <td width="33%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                      <tr>
                                        <td width="45%"><div align="right">Home:</div></td>
                                        <td width="55%"><div align="left">
                                            <input name="home" value="<?php if( isset( $this->cartInfo['basic']['home']) ) echo $this->cartInfo['basic']['home']?>" type="text" class="input1" />
                                        </div></td>
                                      </tr>
                                    </table></td>
                                    <td width="33%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                      <tr>
                                        <td width="45%"><div align="right">Fax:</div></td>
                                        <td width="55%"><div align="left">
                                            <input name="fax" value="<?php if( isset( $this->cartInfo['basic']['fax']) ) echo $this->cartInfo['basic']['fax']?>" type="text" class="input1" />
                                        </div></td>
                                      </tr>
                                    </table></td>
                                  </tr>
                                </table></td>
                              </tr>
                              <tr>
                                <td class="STYLE2"><div align="right">Email</div></td>
                                <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                  <tr>
                                    <td width="30%"><table width="94%" border="0" cellspacing="0" cellpadding="0">
                                      <tr>
                                        <td width="26%"><div align="left"><span style="color:red">Public:</span></div></td>
                                        <td width="74%"><div align="left">
                                            <input name="public" id="public" value="<?php if( isset( $this->cartInfo['basic']['public']) ) echo $this->cartInfo['basic']['public']?>" type="text" class="input2" />
                                        </div></td>
                                      </tr>
                                    </table></td>
                                    <td><table width="100%" border="0" align="right" cellpadding="0" cellspacing="0">
                                      <tr>
                                        <td width="53%"><div align="right">For Chi Institute only:</div></td>
                                        <td width="47%"><div align="left">
                                            <input name="for_chi_institute_only" value="<?php if( isset( $this->cartInfo['basic']['for_chi_institute_only']) ) echo $this->cartInfo['basic']['for_chi_institute_only']?>" type="text" class="input2" />
                                        </div></td>
                                      </tr>
                                    </table></td>
                                  </tr>
                                </table></td>
                              </tr>
                              <tr>
                                <td colspan="2" class="STYLE2"><div align="right">
                                  <table width="100%" border="0" cellspacing="5" cellpadding="0">
                                    <tr>
                                      <td width="50%"><div align="right">
                                       
                                      </div></td>
                                      <td width="50%"><div align="left">
                                        <input type="submit" value="Next Step&gt;" />
                                      </div></td>
                                    </tr>
                                  </table>
                                </div></td>
                                </tr>
                            </table></td>
                            </tr>
                          <tr>
                            <td>&nbsp;</td>
                          </tr>
                          <tr>
                            <td>&nbsp;</td>
                          </tr>
                        </table>
                          </form>
                      <p class="STYLE5" align="center" style='margin-top:6.0pt;margin-right:0cm;
  margin-bottom:6.0pt;margin-left:0cm;text-align:center'>&nbsp;</p>
                      <p>&nbsp;</p>
                      <p>&nbsp;</p></td>
                  </tr>
                </table>
                <!-- InstanceEndEditable --></td>
                
                <script>
                function checkForm(){

                	if( !$("#first_name").val() ){
                		alert( "please fill in your first name." );
            			return false;
                    }

                	if( !$("#middle_name").val() ){
                		alert( "please fill in your middle name." );
            			return false;
                    }

                	if( !$("#last_name").val() ){
                		alert( "please fill in your last name." );
            			return false;
                    }

                	if( !$("#work").val() ){
                		alert( "please fill in your work phone number." );
            			return false;
                    }

                	if( !$("#public").val() ){
                		alert( "please fill in your public email address." );
            			return false;
                    }

                    return true;
                }

                </script>