	<td width="81%" align="center" valign="top"><!-- InstanceBeginEditable name="EditRegion1" -->
                <div align="center"></div>
                <table width="750" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td><p>&nbsp;</p>
                      <p class="STYLE5" align="center" style='margin-top:9.0pt;margin-right:0cm;
  margin-bottom:9.0pt;margin-left:0cm;text-align:center'><b style='mso-bidi-font-weight:
  normal'><span style='font-size:14.0pt' lang="EN-US" xml:lang="EN-US">Chi Institute Australia
                        2012 Small Animal Acupuncture Program
                              <o:p></o:p>
                      </span></b></p>
 
                          <tr>
                            <td><table width="100%" border="1" align="center" cellpadding="10" cellspacing="0" bordercolor="#FFFFFF" bgcolor="#FCFCFC" class="STYLE2">
                              
                              
                              <?php foreach( $this->courses as $id => $course ):?>
                              <tr>
                                <td width="30%" class="STYLE2"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                  <tr>
                                    <td width="28%"><div align="right"><img src="<?php echo $this->baseUrl().$course["image"]?>" width="60" height="60" /></div></td>
                                    <td width="72%" valign="top"><table width="95%" border="0" align="right" cellpadding="0" cellspacing="0">
                                      <tr>
                                        <td><p align="left" class="STYLE4"><strong><?php echo $course["name"]?></strong></p></td>
                                      </tr>
                                      <tr>
                                        <td><div align="left">
                                        <strong>
                                  
                                        	<?php echo during_time( $course["id"] )?>
                                        </strong></div></td>
                                      </tr>
                                    </table>
                                      <div align="center" class="STYLE3">
                                        <div align="left"></div>
                                      </div></td>
                                  </tr>
                                </table></td>
                                <td width="70%" class="STYLE2"><table width="95%" border="0" align="left" cellpadding="0" cellspacing="10">
                                  <tr>
                                    <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                      <tr>
                                        <td width="4%"><div align="right">
                                         
                                        </div></td>
                                        <td width="96%"><div align="left">AU $<?php echo $course["price"]["before"]?> (GST inclusive)paid before <?php echo before_time($course["id"]);?> </div></td>
                                      </tr>
                                    </table></td>
                                  </tr>
                                  <tr>
                                    <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                      <tr>
                                        <td width="4%"><div align="right">
                                           
                                        </div></td>
                                        <td width="96%"><div align="left">AU $<?php echo $course["price"]["now"]?> (GST inclusive)paid <?php echo between_time($course["id"]);?> </div></td>
                                      </tr>
                                    </table></td>
                                  </tr>
                                </table></td>
                              </tr>
                              
                              <?php endforeach;?>
                              
                              
                             
                             
                            
                              <tr>
                                <td colspan="2" class="STYLE2"><div align="center">
                                  <table width="100%" border="0" cellspacing="5" cellpadding="0">
                                    <tr>
                                      <td width="46%"><div align="right">
                                       
                                      </div></td>
                                      <td width="7%"><label>
                                        
                                      </label></td>
                                      <td width="47%"><div align="left">
                                          
                                      </div></td>
                                    </tr>
                                  </table>
                                </div></td>
                                </tr>

                              
                            </table></td>
                            </tr>
                        </table>
                      
                      <p class="STYLE5" align="center" style='margin-top:6.0pt;margin-right:0cm;
  margin-bottom:6.0pt;margin-left:0cm;text-align:center'>&nbsp;</p>
                      <p>&nbsp;</p>
                      <p>&nbsp;</p></td>
                  </tr>
                </table>
                <!-- InstanceEndEditable --></td>
                
 
 <?php 
 function before_time( $courseId ){
 	
 	$course  = TCVM_Product_Factory::Factory()->getById( $courseId );
 	
 	if( $course["time_start"]["month"] == 1 ){
 		$beforeMonth = 12;
 		$beforeYear  = $course["time_start"]["year"] - 1;
 	}else{
 		$beforeMonth = $course["time_start"]["month"] - 1;
 		$beforeYear  = $course["time_start"]["year"];
 	}
 	
 	$beforeTime = mktime( 0 , 0 , 0 , $beforeMonth , 1 , $beforeYear );
 	
 	$rtn = date( "F j,Y" ,  $beforeTime );
 	return $rtn;
 }
 
 function between_time( $courseId ){
 
 	$course  = TCVM_Product_Factory::Factory()->getById( $courseId );
 	
 	if( $course["time_start"]["month"] == 1 ){
 		$beforeMonth = 12;
 		$beforeYear  = $course["time_start"]["year"] - 1;
 	}else{
 		$beforeMonth = $course["time_start"]["month"] - 1;
 		$beforeYear  = $course["time_start"]["year"];
 	}
 	
 	$beforeTime = mktime( 0 , 0 , 0 , $beforeMonth , 1 , $beforeYear );
 	$endtime    = mktime( 0 , 0 , 0 , $course["time_start"]["month"] , $course["time_start"]["date"] , $course["time_start"]["year"] );
 	$rtn = date( "F j" ,  $beforeTime ) . " - " .  date( "F j,Y" ,  $endtime )  ;
 	return $rtn;
 	
 
 }
 
 function during_time($courseId){
 	
 	$course  = TCVM_Product_Factory::Factory()->getById( $courseId );
 	
 	
 	

 	$startTime    = mktime( 0 , 0 , 0 , $course["time_start"]["month"] , $course["time_start"]["date"] , $course["time_start"]["year"] );
 	$endTime    = mktime( 0 , 0 , 0 , $course["time_end"]["month"] , $course["time_end"]["date"] , $course["time_end"]["year"] );
 	$rtn = date( "F j" ,  $startTime ) . " - " .  date( "F j,Y" ,  $endTime )  ;
 	return $rtn;
 	
 }
 
 ?>