			<td width="81%" align="center" valign="top"><!-- InstanceBeginEditable name="EditRegion1" -->
                <div align="center"></div>
                <table width="750" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td><p>&nbsp;</p>
                      <p class="STYLE5" align="center" style='margin-top:9.0pt;margin-right:0cm;
  margin-bottom:9.0pt;margin-left:0cm;text-align:center'><b style='mso-bidi-font-weight:
  normal'><span style='font-size:14.0pt' lang="EN-US" xml:lang="EN-US">Chi Institute Australia
                        2012 Small Animal Acupuncture Program
                              <o:p></o:p>
                      </span></b></p>
                      <p class="STYLE5" align="center" style='margin-top:6.0pt;margin-right:0cm;
  margin-bottom:6.0pt;margin-left:0cm;text-align:center'><b style='mso-bidi-font-weight:
  normal'><span style='font-size:14.0pt' lang="EN-US" xml:lang="EN-US">Class Registration
                        </span></b></p>
                      <form action="" method="post" enctype="multipart/form-data" name="form1" id="form1">
                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                          <tr>
                            <td><div align="left">
                              <p class="STYLE3"><strong>STEP 6: Thanks for ordering the courses!</strong></p> 
                              <p class="STYLE3"><strong>We already generate a order for you, you can <a href="<?php echo $this->url(array("action" => "order" , "controller" => "user"), 'default', true);?>">click here</a> to pay for it.</strong></p> 
                              <p class="STYLE3"><strong>Also you can choose another way to pay the courses,  <a href="<?php echo $this->baseUrl() ?>/form.doc">Here</a> is the docs for the registration form, print and SIGN . Mail and fax (if possible) the signed form with your payment to us. </strong></p>
                            </div></td>
                            </tr>

                        </table>
                          </form>
                      <p class="STYLE5" align="center" style='margin-top:6.0pt;margin-right:0cm;
  margin-bottom:6.0pt;margin-left:0cm;text-align:center'>&nbsp;</p>
                      <p>&nbsp;</p>
                      <p>&nbsp;</p></td>
                  </tr>
                </table>
                <!-- InstanceEndEditable --></td>
                
                  <script>
                function previous(){

              	 	location.href= "<?php echo $this->url(array("action" => "order" , "controller" => "user"), 'default', true);?>";
              	 
              	 }
                
                </script>