			<td width="81%" align="center" valign="top"><!-- InstanceBeginEditable name="EditRegion1" -->
                <div align="center"></div>
                <table width="750" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td><p>&nbsp;</p>
                      <p class="STYLE5" align="center" style='margin-top:9.0pt;margin-right:0cm;
  margin-bottom:9.0pt;margin-left:0cm;text-align:center'><b style='mso-bidi-font-weight:
  normal'><span style='font-size:14.0pt' lang="EN-US" xml:lang="EN-US">Chi Institute Australia
                        2012 Small Animal Acupuncture Program
                              <o:p></o:p>
                      </span></b></p>
                      <p class="STYLE5" align="center" style='margin-top:6.0pt;margin-right:0cm;
  margin-bottom:6.0pt;margin-left:0cm;text-align:center'><b style='mso-bidi-font-weight:
  normal'><span style='font-size:14.0pt' lang="EN-US" xml:lang="EN-US">Class Registration
                        </span></b></p>
                      <form action="" method="post" enctype="multipart/form-data" name="form1" id="form1">
                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                          <tr>
                            <td><div align="left">
                              <p class="STYLE3"><strong>STEP 6:We already generate a Order for you, Please download the form below. Then print and SIGN . Mail and fax (if possible) the signed form with your payment  to us. </strong></p>
                            </div></td>
                            </tr>
                          <tr>
                            <td><table width="100%" border="1" align="center" cellpadding="10" cellspacing="0" bordercolor="#FFFFFF" bgcolor="#FCFCFC" class="STYLE2">
                              <tr>
                                <td width="100%" valign="top" class="STYLE3"><span class="STYLE9"><a href="images/form.doc">Please download 
                                      <label>the form here </label>
                                </a>                                  
                                    <label></label>
                                </span>                                  <label></label></td>
                                </tr>

                              <tr>
                                <td class="STYLE2"><div align="center">
                                  <table width="100%" border="0" cellspacing="5" cellpadding="0">
                                    <tr>
                                      <td>
                                        <div align="center">
                                          <input type="button" onclick="previous();"  value="finish" />
                                        </div></td>
                                      </tr>
                                  </table>
                                </div></td>
                                </tr>
                            </table></td>
                          </tr>
                        </table>
                          </form>
                      <p class="STYLE5" align="center" style='margin-top:6.0pt;margin-right:0cm;
  margin-bottom:6.0pt;margin-left:0cm;text-align:center'>&nbsp;</p>
                      <p>&nbsp;</p>
                      <p>&nbsp;</p></td>
                  </tr>
                </table>
                <!-- InstanceEndEditable --></td>
                
                  <script>
                function previous(){

              	 	location.href= "<?php echo $this->url(array("action" => "order" , "controller" => "user"), 'default', true);?>";
              	 
              	 }
                
                </script>