<td width="81%" align="center" valign="top"><!-- InstanceBeginEditable name="EditRegion1" -->
                <div align="center"></div>
                <table width="750" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td><p>&nbsp;</p>
                      <p class="STYLE5" align="center" style='margin-top:9.0pt;margin-right:0cm;
  margin-bottom:9.0pt;margin-left:0cm;text-align:center'><b style='mso-bidi-font-weight:
  normal'><span style='font-size:14.0pt' lang="EN-US" xml:lang="EN-US">Chi Institute Australia
                        2012 Small Animal Acupuncture Program
                              <o:p></o:p>
                      </span></b></p>
                      <p class="STYLE5" align="center" style='margin-top:6.0pt;margin-right:0cm;
  margin-bottom:6.0pt;margin-left:0cm;text-align:center'><b style='mso-bidi-font-weight:
  normal'><span style='font-size:14.0pt' lang="EN-US" xml:lang="EN-US">Class Registration
                        </span></b></p>
                      <form onsubmit="return checkForm();" id="form1" name="form1" method="post" action="<?php echo $this->url(array("action" => "post-paymethod" , "controller" => "registration"), 'default', true);?>">
                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                          <tr>
                            <td><div align="left">
                              <p style="margin-top:0cm;margin-right:0cm;margin-bottom:3.0pt;
  margin-left:6.0pt;text-indent:-6.0pt">&nbsp;</p>
                              <p class="STYLE3" style="margin-top:0cm;margin-right:0cm;margin-bottom:3.0pt;
  margin-left:6.0pt;text-indent:-6.0pt"><strong>STEP  4: Select Method of Payment for Tuition</strong></p>
                            </div></td>
                            </tr>
                          <tr>
                            <td><table width="100%" border="1" align="center" cellpadding="10" cellspacing="0" bordercolor="#FFFFFF" bgcolor="#FCFCFC" class="STYLE2">
                              <tr>
                                <td colspan="2" class="STYLE2"><div align="right">
                                  <table width="100%" border="0" cellspacing="5" cellpadding="0">
                                    
                                    <tr>
                                      <td><input type="radio" name="paymethod" <?php if( $this->cartInfo['payinfo']['paymethod'] == TCVM_Payment_Imple::PAYMENT_ELECTRONIC_TRANSFER ) echo "checked"?> value="<?php echo TCVM_Payment_Imple::PAYMENT_ELECTRONIC_TRANSFER?>" /></td>
                                      <td colspan="3"><div align="left">Bank Transfer?(please email <span class="STYLE9" style="font-weight: bold"><a href="mailto:admin@tcvm.com.au">admin@tcvm.com</a></span><a href="mailto:admin@tcvm.com.au">.au</a> for detailed instructions)</div></td>
                                    </tr>
                                    <tr>
                                      <td><input type="radio" name="paymethod" value="<?php echo TCVM_Payment_Imple::PAYMENT_PAYPAL_ADAPTIVE?>" <?php if( $this->cartInfo['payinfo']['paymethod'] == TCVM_Payment_Imple::PAYMENT_PAYPAL_ADAPTIVE ) echo "checked"?> /></td>
                                      <td colspan="3"><p align="left">Paypal; (please send tuition  payment to<a href="mailto:naturalvet@earthlink.net" class="STYLE9" style="color: #2b677f; font-weight: bold"> naturalvet@earthlink.net</a>)</p></td>
                                    </tr>
                                    
                                  </table>
                                </div></td>
                                </tr>
                              
                              <tr>
                                <td colspan="2" class="STYLE2"><div align="center">
                                  <table width="100%" border="0" cellspacing="5" cellpadding="0">
                                    <tr>
                                      <td width="46%"><div align="right">
                                          <input type="button" onclick="previous();" value="&lt;Previous Step" />
                                      </div></td>
                                      
                                      <td width="47%"><div align="left">
                                          <input type="submit"  value="Next Step&gt;" />
                                      </div></td>
                                    </tr>
                                  </table>
                                </div></td>
                                </tr>
                            </table></td>
                          </tr>
                        </table>
                          </form>
                      <p class="STYLE5" align="center" style='margin-top:6.0pt;margin-right:0cm;
  margin-bottom:6.0pt;margin-left:0cm;text-align:center'>&nbsp;</p>
                      <p>&nbsp;</p>
                      <p>&nbsp;</p></td>
                  </tr>
                </table>
                
                <script>
              
                	function checkForm(){
                		
                		var selected = $('input:checked').val();
                	
                		if( !selected ){
							alert( "please choose payment method" );
							return false;
	                    }

                    	return true;
                    	
                		
                    	}
                	
                	function previous(){

                  	 	location.href= "<?php echo $this->url(array("action" => "product" , "controller" => "registration"), 'default', true);?>";
                  	 
                  	 }
                </script>
