<td width="81%" align="center" valign="top"><!-- InstanceBeginEditable name="EditRegion1" -->
                <div align="center"></div>
                <table width="750" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td><p>&nbsp;</p>
                      <p class="STYLE5" align="center" style='margin-top:9.0pt;margin-right:0cm;
  margin-bottom:9.0pt;margin-left:0cm;text-align:center'><b style='mso-bidi-font-weight:
  normal'><span style='font-size:14.0pt' lang="EN-US" xml:lang="EN-US">Chi Institute Australia
                        2012 Small Animal Acupuncture Program
                              <o:p></o:p>
                      </span></b></p>
                      <p class="STYLE5" align="center" style='margin-top:6.0pt;margin-right:0cm;
  margin-bottom:6.0pt;margin-left:0cm;text-align:center'><b style='mso-bidi-font-weight:
  normal'><span style='font-size:14.0pt' lang="EN-US" xml:lang="EN-US">Class Registration
                        </span></b></p>
                      <form action="" method="post" enctype="multipart/form-data" name="form1" id="form1">
                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                          <tr>
                            <td><div align="left">
                              <p class="STYLE3"><strong>STEP  5:If this is the first time you are registering  courses with us, please attach a brief biographical sketch and a recent  photograph of yourself. A non-refundable $100 application fee is required for  all new students. </strong></p>
                            </div></td>
                            </tr>
                          <tr>
                            <td><table width="100%" border="1" align="center" cellpadding="10" cellspacing="0" bordercolor="#FFFFFF" bgcolor="#FCFCFC" class="STYLE2">
                              <tr>
                                <td valign="top" class="STYLE3"> <div align="right">Type you brief biographical sketch</div></td>
                                <td class="STYLE2"><label>
                                  <div align="left">
                                    <textarea name="textarea" cols="80" rows="4"></textarea>
                                    </div>
                                </label></td>
                              </tr>
                              <tr>
                                <td valign="top" class="STYLE3"><div align="right">Or upload your  brief biographical sketch</div></td>
                                <td class="STYLE2"><table width="100%" border="0" cellspacing="5" cellpadding="0">
                                  <tr>
                                    <td width="59%"><input name="file2" type="file" size="40" /></td>
                                    <td width="41%"><div align="left">
                                        <input type="submit" name="Submit32" value="upload" />
                                    </div></td>
                                  </tr>
                                </table></td>
                              </tr>
                              <tr>
                                <td class="STYLE3"><div align="right">upload your <strong>recent</strong> photo </div></td>
                                <td class="STYLE2"><table width="100%" border="0" cellspacing="5" cellpadding="0">
                                  <tr>
                                    <td width="59%"><input name="file" type="file" size="40" /></td>
                                    <td width="41%"><div align="left">
                                      <input type="submit" name="Submit3" value="upload" />
                                    </div></td>
                                  </tr>
                                </table></td>
                              </tr>
                              <tr>
                                <td width="14%" class="STYLE2"><div align="right"><strong>How did you hear about this program?</strong></div></td>
                                <td width="86%" class="STYLE2"><table width="100%" border="0" cellspacing="5" cellpadding="0">
                                  <tr>
                                    <td width="25%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                        <tr>
                                          <td width="10%"><input type="checkbox" name="checkbox22" value="checkbox" /></td>
                                          <td width="24%">Friends</td>
                                          <td width="66%"><div align="left">
                                              <input name="textfield2332242" type="text" class="input1" />
                                          </div></td>
                                        </tr>
                                    </table></td>
                                    <td width="25%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                        <tr>
                                          <td width="10%"><input type="checkbox" name="checkbox222" value="checkbox" /></td>
                                          <td width="16%">Show</td>
                                          <td width="74%"><div align="left">
                                              <input name="textfield23322422" type="text" class="input1" />
                                          </div></td>
                                        </tr>
                                    </table></td>
                                    <td width="25%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                        <tr>
                                          <td width="10%"><input type="checkbox" name="checkbox2222" value="checkbox" /></td>
                                          <td width="16%">Magazine</td>
                                          <td width="74%"><div align="left">
                                              <input name="textfield233224222" type="text" class="input1" />
                                          </div></td>
                                        </tr>
                                    </table></td>
                                  </tr>
                                  <tr>
                                    <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                        <tr>
                                          <td width="10%"><input type="checkbox" name="checkbox223" value="checkbox" /></td>
                                          <td width="24%">Internet</td>
                                          <td width="66%"><div align="left">
                                              <input name="textfield23322423" type="text" class="input1" />
                                          </div></td>
                                        </tr>
                                    </table></td>
                                    <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                        <tr>
                                          <td width="11%"><input type="checkbox" name="checkbox2232" value="checkbox" /></td>
                                          <td width="24%"><div align="left">Flyer</div></td>
                                          <td width="27%"><div align="right">
                                              <input type="checkbox" name="checkbox22322" value="checkbox" />
                                          </div></td>
                                          <td width="38%"><div align="left">Email</div></td>
                                        </tr>
                                    </table></td>
                                    <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                        <tr>
                                          <td width="10%"><input type="checkbox" name="checkbox22222" value="checkbox" /></td>
                                          <td width="27%"><div align="left">Other</div></td>
                                          <td width="63%"><div align="left">
                                              <input name="textfield2332242222" type="text" class="input1" />
                                          </div></td>
                                        </tr>
                                    </table></td>
                                  </tr>
                                </table></td>
                              </tr>
                              <tr>
                                <td colspan="2" class="STYLE2"><div align="center">
                                  <table width="100%" border="0" cellspacing="5" cellpadding="0">
                                    <tr>
                                      <td width="46%"><div align="right">
                                          <input type="submit" name="Submit" value="&lt;Previous Step" />
                                      </div></td>
                                      <td width="7%"><label>
                                        <input type="submit" name="Submit33" value="Save" />
                                      </label></td>
                                      <td width="47%"><div align="left">
                                          <input type="submit" name="Submit2" value="Next Step&gt;" />
                                      </div></td>
                                    </tr>
                                  </table>
                                </div></td>
                                </tr>
                            </table></td>
                          </tr>
                        </table>
                          </form>
                      <p class="STYLE5" align="center" style='margin-top:6.0pt;margin-right:0cm;
  margin-bottom:6.0pt;margin-left:0cm;text-align:center'>&nbsp;</p>
                      <p>&nbsp;</p>
                      <p>&nbsp;</p></td>
                  </tr>
                </table>
                <!-- InstanceEndEditable --></td>